### ISSUE TITLE
[Visual QA] Level 2 Heros

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#102]
The images on the Sponsorship template & Services detail template are shorter than the images on the pages one level up. In comps, they are 660px x 660px on level 1 (ex: Audio) and 660px x 555px on level 2 (Podcast).

The shorter hero area is meant to indicate a lower page level.

This is not a huge design priority if building this variation is a huge challenge, but wanted to document.

**Comment by mindywagner** [comment]
In Figma: 
![Screen Shot 2019-11-04 at 11 06 10 AM](https://user-images.githubusercontent.com/67819/68136355-21dab480-fef3-11e9-8757-f50a7c2ce550.png)

**Comment by mindywagner** [comment]
Did we decide not to update this?

**Comment by gracecanfield** [comment]
@justinvandenberg Could you weigh in on @mindywagner 's question above?
