### ISSUE TITLE
[QA] Sponsorship page > IE11 issues

### ISSUE THREAD

**Issue by jessicasheng15** [vigetlabs/npm#106]
Happening on Windows IE 11 (desktop):

https://live-national-public-media-v2.pantheonsite.io/sponsorship/podcast-sponsorship/

**1. The product cards are not constrained by an aspect ratio so they are enlarged and bleed across the page.**
![image](https://user-images.githubusercontent.com/36860796/68163768-45205680-ff29-11e9-819f-a1c11f39be99.png)

**2. First two Program cards are shorter in height.**
![image](https://user-images.githubusercontent.com/36860796/68163992-bb24bd80-ff29-11e9-85e2-1cd6c7fa4153.png)

**Comment by jessicasheng15** [comment]
Program card issues persist on IE11 on this page. Program card thumbnails are blown out and text is lost.

Screenshots:
* https://www.dropbox.com/s/xpnyy5zzabw9i6w/Screenshot%202019-11-18%2019.12.59.png?dl=0
* https://www.dropbox.com/s/xhsxo7y6rugkuog/Screenshot%202019-11-18%2019.14.03.png?dl=0

**Comment by gracecanfield** [comment]
@jessicasheng15 did you mean to close this?

**Comment by jessicasheng15** [comment]
Nope, thanks for the catch!

**Comment by gracecanfield** [comment]
No longer applicable (re-tested).
