### ISSUE TITLE
[QA] Products index > Cards are missing hover state on desktop

### ISSUE THREAD

**Issue by jessicasheng15** [vigetlabs/npm#109]
**Current:**
![image](https://user-images.githubusercontent.com/36860796/68216209-8dce2300-ffae-11e9-9927-13416ad57c32.png)

* All cards have dropshadow regardless of hover
* Entire card surface area is not interactive as suggested by comps, only the Details link is 

**Desired (or suggested by comps)**
![image](https://user-images.githubusercontent.com/36860796/68216184-8444bb00-ffae-11e9-9a6a-75d3c1a57dc4.png)

**Comment by gracecanfield** [comment]
This is a dupe for an existing issue - closin out
