### ISSUE TITLE
Test font approach (cross-domain hosting)

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#11]
### Overview

* **Page/Element:** Gotham fonts on site
* **Example link:** N/A
* **Related client Trello card:** https://trello.com/c/Evb4FBKE
	
### Details

With regard to using Gotham on the new site, the client sent these instructions:

>We can’t have you re-host the fonts; instead, you need to directly call the font CSS files from the npr.org location. GothamSSm (2 weights, normal and italics) is here: https://s.npr.org/templates/css/fonts/GothamSSm.css and Knockout (we only license one weight, Knockout 31) is here: https://s.npr.org/templates/css/fonts/Knockout.css. We do not need to do anything about the domain.

You'd brought up that this could cause some CORS (cross-domain resource tracking) issues, and that we'd need to test this approach out. 

**Task:** Test the approach out and confirm whether we can use this approach, or whether we need to handle fonts in a different way.

**Comment by justinvandenberg** [comment]
@gracecanfield can you confirm this is working correctly on staging? I have the Gotham font installed.

**Comment by gracecanfield** [comment]
@justinvandenberg Fonts look good to me on staging! Does that mean that we can assume the font hosting approach works and close this out?

**Comment by gracecanfield** [comment]
Oh wait...I also have the Goth
