### ISSUE TITLE
[QA] Products Index > No results message

### ISSUE THREAD

**Issue by jessicasheng15** [vigetlabs/npm#110]
Just double-checking that I shouldn't be expecting to see something different when there are no matching results for combined filters.

To reproduce:

1. Navigate to https://live-national-public-media-v2.pantheonsite.io/products/
2. Select 'Video' format filter
3. Select 'Desktop' platform filter 
4. User is shown empty page:
![image](https://user-images.githubusercontent.com/36860796/68216829-8e1aee00-ffaf-11e9-8f68-c47285630df4.png)

**Comment by gracecanfield** [comment]
@justinvandenberg Can you display a message that says something like `There are no results for the selected filters—please try again.` (we should also still be showing filters on the page so they can make a different selection.)

**Comment by jessicasheng15** [comment]
Looks good! In case you'd like to reproduce: select 'Custom' format > External Platforms platform.
