### ISSUE TITLE
[QA] Reports polish

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#117]
* [x] Insights has the option to pick video or image in the right-hand column (to be featured). Reports doesn’t have this, but needs it - and the featured video should display if it’s used in the Insights Index hero block.

**Comment by gracecanfield** [comment]
If a video is uploaded, it should display instead of the Image (it should override the Image field).

**Comment by justinvandenberg** [comment]
@gracecanfield this is only for the hero block correct (one with a featured article or report)?

**Comment by gracecanfield** [comment]
@justinvandenberg Let's assume it should be for any of the spots on the featured blocks on the page.
