### ISSUE TITLE
[QA] Text block: Polish

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#118]
* [x] CTA isn’t displaying with the text wrapping left ([screenshot](https://www.dropbox.com/s/6ebnln04l8mwvkm/Screenshot%202019-11-05%2010.35.09.png?dl=0) - https://live-national-public-media-v2.pantheonsite.io/page-blocks/
* [x] Need a fine print style ([comp screenshot](https://www.dropbox.com/s/57t1pzccq5opb0v/Screenshot%202019-11-05%2010.05.37.png?dl=0) 
* [x] Remove text color options
* [x] Remove “Insert Read More link” option?

**Comment by justinvandenberg** [comment]
@gracecanfield the text below the CTA should wrap. Looks like the CTA is just at the very bottom.

**Comment by justinvandenberg** [comment]
Also, the small text is under the "Format" menu.
