### ISSUE TITLE
[QA] Article detail polish

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#120]
In cases where there isn't a hero image on the page, [this top section of the page](https://www.dropbox.com/s/koaya2n5co1cyrh/Screenshot%202019-11-05%2014.01.03.png?dl=0) doesn't dispaly. 

Please update so the "Insights" label, title, type (article or report), and date show up even if the hero block isn't the first block on the page. 

Example: https://live-national-public-media-v2.pantheonsite.io/insights/test-article/

Screenshot of actual: https://www.dropbox.com/s/2yifd5syybxbrdb/Screenshot%202019-11-05%2014.02.25.png?dl=0

**Comment by justinvandenberg** [comment]
@gracecanfield I think that you just need to add the block (with or without the image).

**Comment by gracecanfield** [comment]
Couple more QA fixes needed:
* [ ] Reduce padding between hero block and next block (match comp). (see [side by side screenshot](https://www.dropbox.com/s/cmqo188hf4ekqvl/Screenshot%202019-11-05%2009.53.35.png?dl=0). Same with padding beneath image block. Example page: https://live-national-public-media-v2.pantheonsite.io/insights/fromage-frais-bavarian-bergkase-cheese-triangles/

**Comment by justinvandenberg** [comment]
@gracecanfield isn't this one already done? I think Mindy had a similar ticket.

**Comment by gracecanfield** [comment]
Probably 🤦‍♀  I'll close
