### ISSUE TITLE
[Question] Report Detail > Should there be a Related Insights section?

### ISSUE THREAD

**Issue by jessicasheng15** [vigetlabs/npm#128]
Assuming this is a CMS entry thing, but I don't see a `Related Insights` section below the grid of user profile videos based on comps.

https://live-national-public-media-v2.pantheonsite.io/insights/reports/test-report-1/

**Currently:**
![image](https://user-images.githubusercontent.com/36860796/68309498-89703b80-007c-11ea-973b-0a69475d829c.png)

**Comment by gracecanfield** [comment]
Yep, just a CMS thing! Thanks for flagging, though!
