### ISSUE TITLE
[QA] Programs Index > Clicking out of modal jumps user to top of page (Mac Safari)

### ISSUE THREAD

**Issue by jessicasheng15** [vigetlabs/npm#133]
**Browser/Device:** Mac Safari

https://live-national-public-media-v2.pantheonsite.io/programs/

**Description**: After a user scrolls down the page, clicks on a tile to open the modal, then clicks back out, it jumps back to the top of the page. (Recording below)

To reproduce:

1. Navigate to https://live-national-public-media-v2.pantheonsite.io/programs/
2. Scroll down page.
3. Click on a Program tile to open modal.
4. Click 'x' OR click outside of tile to close modal.
5. Observe the page jump back to the top.

**Recording:** https://recordit.co/S9mjiAcJ5T

**Comment by justinvandenberg** [comment]
@gracecanfield this is due to the browser scrolling back to the focused (program clicked to open the modal). I can prevent that but then we run into some a11y issues. I'll ask our a11y gurus (Megan and Jeremy) if they have any ideas.

**Comment by justinvandenberg** [comment]
I asked around and we shouldn't mess with default browser functionality.

**Comment by gracecanfield** [comment]
Okay; closing this out.
