### ISSUE TITLE
Various blocks: Tighten up padding

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#138]
## Overview

**Elements:**
* [ ] Product page hero
* [ ] Quote block
* [ ] Program block
* [ ] Featured work block
* [ ] Featured content block
* [ ] Related work block
* [ ] Audience carousel
* [ ] Homepage quote block (with listener portrait)
* [ ] Homepage hero

**Example URL**
https://live-national-public-media-v2.pantheonsite.io/
https://live-national-public-media-v2.pantheonsite.io/audience/

**Related Trello card**
https://trello.com/c/a3TwQcEg
	
## Details

**Summary:**
Please reduce padding throughout on blocks

**Current vs. Desired state:**
Please reduce padding throughout consistently with the reduction requested on the nav padding. Blocks are so large at larger breakpoints that you cannot see the whole thing in one screen. Blocks should be small enough where you see the next block before scrolling. For example: homepage- user should be able to see NPM logo and NPR logos on program cards on the same screen without scrolling.

This applies to many of the pages, specifically the blocks in the screenshots i've attached. When viewed on my macbook laptop (1280 × 650), the block either takes up the entire screen, or is bigger than the screen, and we'd like the padding to be reduced so that there is not only one block that can be seen on the page.

@mindywagner Could you provide guidance for @justinvandenberg on this one, for the blocks mentioned above? NPM would just like padding to be tightened up. 

<img width="1392" alt="Audience_segments_block" src="https://user-images.githubusercontent.com/6934226/68406971-c1e14980-0150-11ea-8f73-00bf3ed26f09.png">
<img width="1392" alt="Featured_work_section" src="https://user-images.githubusercontent.com/6934226/68406977-c3ab0d00-0150-11ea-8c18-c634e3ace4f6.png">
<img width="1392" alt="Homepage_hero" src="https://user-images.githubusercontent.com/6934226/68406987-c60d6700-0150-11ea-8784-7255095adc7a.png">
<img width="1392" alt="Homepage-Listeners_stats_block" src="https://user-images.githubusercontent.com/6934226/68406991-c73e9400-0150-11ea-93d0-be0361ea3909.png">
<img width="1392" alt="Product_Detail" src="https://user-images.githubusercontent.com/6934226/68406998-c9085780-0150-11ea-94ae-f8af3c186405.png">
<img width="1392" alt="Products_2-ups_1" src="https://user-images.githubusercontent.com/6934226/68407006-cb6ab180-0150-11ea-96aa-c830b56dc64e.png">
<img width="1392" alt="Products_2-ups" src="https://user-images.githubusercontent.com/6934226/68407009-cd347500-0150-11ea-9a54-c0aecd82fd21.png">
<img width="1392" alt="Program_Cards" src="https://user-images.githubusercontent.com/6934226/68407013-cefe3880-0150-11ea-95e1-537c6b953b2e.png">
<img width="1392" alt="Quote_Block" src="https://user-images.githubusercontent.com/6934226/68407016-d02f6580-0150-11ea-9ae0-7a14dc0f44f8.png">
<img width="1392" alt="Work_blocks" src="https://user-images.githubusercontent.com/6934226/68407019-d1f92900-0150-11ea-9853-0a4e2a766aa8.png">

**Comment by mindywagner** [comment]
Should I be redesigning each of these elements individually? Globally, there are certain paddings I set that most elements use. For instance most elements have 50px padding at top/bottom on desktop, and 100px padding between one element and the next. We could reduce this universally *if* it's applied in a universal way in the code.

**Comment by mindywagner** [comment]
I think in order to reduce padding in a way that is going to look consistent & good, I'd have to revisit all pages. Changing just top/bottom padding without changing side padding, and perhaps also font size and leading, is going to look bad.

**Comment by justinvandenberg** [comment]
@mindywagner I have a global class that handles elements with the same top/bottom padding. It currently goes 50/75/100. I think that would target ~50% of the elements.

**Comment by mindywagner** [comment]
I have individual tickets in for the quite a few padding things I saw when I QA'd - and I'm seeing more on pages I haven't QA'd yet. These are things that aren't consistent with comps. I think we should address those *first*, then adjust the global padding that *is* consistent with comps but that they now want lessened, and see where we're at. @gracecanfield does that make sense to you?

**Comment by gracecanfield** [comment]
We let NPM know that we made some tweaks and requested that they re-review the site. We can revisit additional padding changes if needed during out QA/polish week after we come back from pause.
