### ISSUE TITLE
[Visual QA] > Get Started > Form fields layout

### ISSUE THREAD

**Issue by jessicasheng15** [vigetlabs/npm#141]
https://live-national-public-media-v2.pantheonsite.io/get-started/

The layout of the form fields do not match the comps. They are currently stacked vertically.

**Currently:**
https://www.dropbox.com/s/7u0uelld4vcvuad/Screenshot%202019-11-07%2011.52.02.png?dl=0

**Comps:**
https://www.dropbox.com/s/rkamvdgb4vb8dx6/Screenshot%202019-11-07%2011.51.44.png?dl=0

**Comment by gracecanfield** [comment]
fixed!
