### ISSUE TITLE
[Visual QA] Global Header - Padding, Weight, & Sizing 

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#149]
- Padding for the header is about 20px off (probably 10 on top and bottom?)
- Contact button isn't sized right (this button is smaller than site-wide buttons on purpose, to make the header slimmer)
- Font weight for the main nav items & secondary nav items in the dropdown should be 500 (right now it's 700) Only the tertiary links (Podcast, Radio, Voice, PBS) should be bolded 
- Logo & Contact Us button were intended to line up with the outer-most content container, but I think NPM submitted their own ticket in about this so maybe it was changed to what they wanted

![header](https://user-images.githubusercontent.com/67819/68485274-02060200-020d-11ea-958d-01804548a823.png)

**Comment by justinvandenberg** [comment]
@mindywagner we don't actually have access to 500 font weight in the linked NPR stylesheet. Just 400 and 700.

**Comment by mindywagner** [comment]
Ah, ok. Let's drop it down to the regular weight then. If they want it a bit bolder we can ask them to get the middle weight.

**Comment by justinvandenberg** [comment]
@mindywagner same with the headings in the dropdown?

**Comment by mindywagner** [comment]
yep!

**Comment by mindywagner** [comment]
Small tweaks:

The tertiary links in the dropdown (Podcast | Radio | Voice and PBS) should be bold. Primary and Secondary are good now. 

Let's move the primary nav items another 20px to the right so the Audience link isn't s close to the NPM logo on larger breakpoints (before it collapses).  

Can we add a highlight state for the primary nav so users know what section they're in? Snapshot from comps:
![Screen Shot 2019-11-13 at 9 04 23 AM](https://user-images.githubusercontent.com/67819/68771069-491d3a00-05f5-11ea-88b7-33ac4dee8647.png)
