### ISSUE TITLE
[Visual QA] Work Detail - Mobile

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#152]
Tighten up the padding between text & image in the hero - looks like it's about 70px now; can be tightened up to ~40px

<img width="309" alt="Screen Shot 2019-11-08 at 10 48 22 AM" src="https://user-images.githubusercontent.com/67819/68489574-6200a680-0215-11ea-9e0e-6e12068f1f94.png">

**Comment by justinvandenberg** [comment]
@mindywagner this looks like it's due to the space in the image (for the drop shadow). Can I safely eliminate the padding and assume all the laptop/phone/tablet templates have the same amount of space baked in?

**Comment by mindywagner** [comment]
The spacing for all three should be pretty close if not exact - the templates for the case study hero areas are in Figma in the Master Components > Styles board, in Hero/Header areas (this is what the PSD templates NPM will use are created from)

![Screen Shot 2019-11-11 at 5 00 38 PM](https://user-images.githubusercontent.com/67819/68624487-ee74c880-04a4-11ea-9d23-b329de776b05.png)
