### ISSUE TITLE
[Visual QA] Work Detail - Modal

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#153]
Modal for visual examples should match the comp. 

Buildout:
<img width="371" alt="Screen Shot 2019-11-08 at 10 48 45 AM" src="https://user-images.githubusercontent.com/67819/68489680-91afae80-0215-11ea-887e-c91359844eca.png">

Comp:
![Image Modal](https://user-images.githubusercontent.com/67819/68489707-9bd1ad00-0215-11ea-9d24-375a7685b165.png)

**Comment by justinvandenberg** [comment]
@mindywagner should the buttons/caption float over the image with the image being edge to edge?

**Comment by mindywagner** [comment]
The way I have this built in Figma, the image is the size they've already created, but the background is the same color as the background they baked into the image so that it appears to be floating. I would build it that way. 
![Screen Shot 2019-11-11 at 2 09 02 PM](https://user-images.githubusercontent.com/67819/68613505-e741c080-048c-11ea-9a15-21d0d087ccb9.png)

**Comment by justinvandenberg** [comment]
@mindywagner will the background color be baked into the image template?

**Comment by mindywagner** [comment]
I actually didn't make an image template for these - this uses the current images on their site (knowing they wouldn't want to recreate all of these) - but yes, the background color is baked in

**Comment by mindywagner** [comment]
you can see examples by clicking on the visual examples in their portfolio: https://www.nationalpublicmedia.com/npmcreative/portfolio/target/

Oddly, it looks like they're using two different background colors - the lighter for table and desktop, a slightly darker one for mobile. Let's stick with the lighter one for our modal, and the darker examples can just stand out a bit from the background.

**Comment by mindywagner** [comment]
Sadness that they baked in an outline on these.... guess this is as good as we can get since that's the case.
