### ISSUE TITLE
[Visual QA] Audience - Mobile

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#156]
The audience image should go edge-to-edge on mobile.  It's about 30px off on the right.

![Screen Shot 2019-11-08 at 2 53 25 PM](https://user-images.githubusercontent.com/67819/68507505-0ac0fd00-023a-11ea-8bb3-f17f06cba3b2.png)

The stat background image should drop out on mobile so the text is readable. 
![Screen Shot 2019-11-08 at 3 18 38 PM](https://user-images.githubusercontent.com/67819/68507977-2973c380-023b-11ea-8f90-0eef55b820f7.png)

**Comment by mindywagner** [comment]
This 2nd item from above still isn't done:
![Screen Shot 2019-11-18 at 1 28 53 PM](https://user-images.githubusercontent.com/67819/69079160-62642300-0a07-11ea-90ce-7a2ede5c5391.png)

**Comment by gracecanfield** [comment]
I believe these are both now N/A
