### ISSUE TITLE
[Visual QA] Report template

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#158]
**Desktop:**

Let's change the top/bottom padding for the feature area to 50px, knowing NPM wants to cut down on spacing. 

Result:
![Screen Shot 2019-11-08 at 4 59 05 PM](https://user-images.githubusercontent.com/67819/68513506-30093780-0249-11ea-81b6-b696915669e9.png)

__________

Webinar section should have the audio background in it (looks like it got shifted somehow in Figma - I moved it back up)
Comp:
![Screen Shot 2019-11-08 at 5 01 20 PM](https://user-images.githubusercontent.com/67819/68513609-7a8ab400-0249-11ea-879f-6a418aa32b1c.png)

__________

Video section should have an h3 headline instead of an h2 headline
Buildout:
![Screen Shot 2019-11-08 at 5 01 01 PM](https://user-images.githubusercontent.com/67819/68513638-8a09fd00-0249-11ea-88b6-5721aaf8fb04.png)

Comp:
![Screen Shot 2019-11-08 at 5 01 05 PM](https://user-images.githubusercontent.com/67819/68513643-8d04ed80-0249-11ea-956d-687913148c5b.png)

__________

Related Articles section - needs a separator & fixed padding between videos/related

Buildout:
![Screen Shot 2019-11-08 at 5 04 13 PM](https://user-images.githubusercontent.com/67819/68513791-ecfb9400-0249-11ea-93bb-c06e6e275d53.png)

Comp:
![Screen Shot 2019-11-08 at 5 05 32 PM](https://user-images.githubusercontent.com/67819/68513816-fd137380-0249-11ea-8dba-6bf59134eb68.png)

**Comment by mindywagner** [comment]
**MOBILE:**

Report cover isn't centered on mobile
Buildout:
![Screen Shot 2019-11-08 at 5 06 55 PM](https://user-images.githubusercontent.com/67819/68513897-351ab680-024a-11ea-88eb-858a147e231d.png)

____

Adjust padding between Large Article blocks - looks like it's 60px between Read More & the separator, and 50px between separator and the image for the next block. Let's cut that to 30px for each. 

Buildout:
![Screen Shot 2019-11-08 at 5 10 41 PM](https://user-images.githubusercontent.com/67819/68514076-bbcf9380-024a-11ea-9b4d-3c4fecc5ed59.png)

Adjustment result: 
![Screen Shot 2019-11-08 at 5 08 53 PM](https://user-images.githubusercontent.com/67819/68514088-c5f19200-024a-11ea-80ea-16e543d94ff3.png)

____

Padding at the bottom of the page (below last element & before footer) is about 110px currently - let's cut that to 50px

Buildout:
![Screen Shot 2019-11-08 at 5 13 18 PM](https://user-images.githubusercontent.com/67819/68514213-1537c280-024b-11ea-8e18-cef87daa5439.png)

**Comment by justinvandenberg** [comment]
@mindywagner do you want the footer to always be 50px below the content? It's currently 50px/75px/100px from mobile to desktop. This would have to be global change as the Insights block is used on most of the pages.

**Comment by mindywagner** [comment]
The screenshot/padding I was talking about was for mobile, but it's a lot bigger than 50px - probably because the element above it also has default padding on it?
