### ISSUE TITLE
[Visual QA] Individual Article Page

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#159]
**Desktop:**

The regular images added to posts are the wrong aspect ratio. Comp is 960x650. Buildout is 1080x960. Adjusting will help with the "more on the screen at one time" issue. 

___________

Blockquote element should have 50px padding above it and 50px padding below it. Right now it has 50px above but only 30px below. 

Line-height should be 140% - right now it's 160%

![Screen Shot 2019-11-08 at 5 19 06 PM](https://user-images.githubusercontent.com/67819/68514527-f980ec00-024b-11ea-93d0-695e9552c05e.png)

___________

Spacing between the headline and the date needs to be tightened up. Headline bottom padding here is 30px - let's knock it down to 10px. 
 
Let's also knock bottom padding for the Insights eyebrow from 20px down to 10px.

Buildout:
![Screen Shot 2019-11-08 at 5 29 13 PM](https://user-images.githubusercontent.com/67819/68514966-56c96d00-024d-11ea-964f-3d76603be611.png)

**Comment by mindywagner** [comment]
**MOBILE:**

Article header:

Padding between the eyebrow or headline &  the top of the page should be 20px on mobile - currently measuring at 50px.

Article headline (Test Article 1) is set as an H1 - should be larger than mobile H2s, but is currently the same font size - let's update to 36px. 

Result of adjustments:
![Screen Shot 2019-11-08 at 5 34 37 PM](https://user-images.githubusercontent.com/67819/68515184-0ef71580-024e-11ea-8fc9-eab1a56a8639.png)

___________

Blockquote:
- Let's make the text size 24px (currently 20px)
- Let's tighten the line height on mobile to 140%
- Update to padding made on desktop (noted above) should also fix the padding here 

___________

Global: Mobile body copy line height throughout should be 160% - currently looks like it's at 140%
Mobile body copy font size should be 16px. Can't tell for sure if it's 16 or 18, just wanted to double check.
___________

Global: Source text should be italicized

**Comment by mindywagner** [comment]
Image ratio should also be fixed for 2-up images seen on the page blocks page. 

Buildout:
![Screen Shot 2019-11-08 at 5 53 16 PM](https://user-images.githubusercontent.com/67819/68515973-b5441a80-0250-11ea-8757-e3c8084078bf.png)

**Comment by justinvandenberg** [comment]
@mindywagner the image block isn't constraining image aspect ratios  as of right now. It's used for the single image and across the site. Should I constrain them? I could see that messing with them.

**Comment by mindywagner** [comment]
Could we at least make sure the ratio we suggest to them in the CMS matches the ratio from the comp? That way we don't lock them in, but they can get the effect they see in the comps.

**Comment by mindywagner** [comment]
**Desktop:**

- [ ] **Paragraphs (or headlines?) need padding adjustments.** Weirdly, some seem to have them and some don't when put into the WYSIWYG. See:
 ![Screen Shot 2019-11-18 at 12 42 08 PM](https://user-images.githubusercontent.com/67819/69076160-e36bec00-0a00-11ea-9b0e-d54c88d9c603.png)
vs.
![Screen Shot 2019-11-18 at 12 42 16 PM](https://user-images.githubusercontent.com/67819/69076174-e961cd00-0a00-11ea-9065-3e6056b6728d.png)
[Test Article](https://live-national-public-media-v2.pantheonsite.io/insights/articles/test-article-11/)
- [ ] ---------------
- [ ] 
- [ ] **Hero image bottom padding needs adjustment.** There's a few layers of padding happening here, so I'm not sure where to adjust it, but there should only be 50px between the hero and the next element. 
- [ ] 
- [ ] [Comp:](https://www.figma.com/file/NmTYeQFyu7XPlzTMSKFOzF/NPM-Comps-For-Buildout?node-id=1182%3A36983)
- [ ] ![Screen Shot 2019-11-18 at 12 44 08 PM](https://user-images.githubusercontent.com/67819/69076299-2d54d200-0a01-11ea-9d20-b2fd7507aead.png)
- [ ] 
- [ ] [Buildout:](https://live-national-public-media-v2.pantheonsite.io/insights/articles/test-article-11/)
- [ ] ![Screen Shot 2019-11-18 at 11 33 45 AM](https://user-images.githubusercontent.com/67819/69076310-35147680-0a01-11ea-9804-ecc8eb1a852c.png)
- [ ] ![Screen Shot 2019-11-18 at 11 37 37 AM](https://user-images.githubusercontent.com/67819/69076459-845aa700-0a01-11ea-89ea-4c6c7b547670.png)
- [ ] ![Screen Shot 2019-11-18 at 11 37 50 AM](https://user-images.githubusercontent.com/67819/69076461-86bd0100-0a01-11ea-82e7-8d1a1ded8605.png)
- [ ] 
- [ ] ---------------
- [ ] 
- [ ] Blockquote padding needs adjustment - should have 50px of padding below the red line. It's currently bumping right up against the next element. 
- [ ] ![Screen Shot 2019-11-18 at 12 48 49 PM](https://user-images.githubusercontent.com/67819/69076617-dc91a900-0a01-11ea-97b3-a6404db23a25.png)
- [ ] 
- [ ] ---------------
- [ ] 
- [ ] Font stack: 
- [ ] Font sizes for the iInsights template should be as follows:
- [ ] h1 - 48px
- [ ] h2 - 36px
- [ ] h3 - 24px 
- [ ] h4 - 22px 
- [ ] h5 - was designed to give them a section label style. Is that not possible? 
- [ ] 
- [ ] [Comp:](https://www.figma.com/file/NmTYeQFyu7XPlzTMSKFOzF/NPM-Comps-For-Buildout?node-id=1329%3A37913)
- [ ] ![Screen Shot 2019-11-18 at 12 52 49 PM](https://user-images.githubusercontent.com/67819/69076857-588bf100-0a02-11ea-8a7e-f6dcf75c0993.png)
- [ ] 
- [ ] ---------------

**Comment by gracecanfield** [comment]
@mindywagner Is this ticket still applicable? (If a bunch of items aren't but some are, want to just spin up a new, consolidated ticket?)
