### ISSUE TITLE
[Visual QA] Video Embeds

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#162]
In videos throughout - is there a way to turn off titles, avatar/logo, and update the button to the one seen in comps?

Buildout:
![Screen Shot 2019-11-08 at 5 07 41 PM](https://user-images.githubusercontent.com/67819/68516072-0227f100-0251-11ea-9506-cb5e954b02b8.png)

Comp:
![Screen Shot 2019-11-08 at 5 57 22 PM](https://user-images.githubusercontent.com/67819/68516150-3dc2bb00-0251-11ea-8695-d25423e25cec.png)

Related - videos need the ability to add a headline. See comp above.

**Comment by justinvandenberg** [comment]
@mindywagner YouTube removed that option last year 😞

**Comment by mindywagner** [comment]
Really? UGH.
