### ISSUE TITLE
[Visual QA] Missing 1-up Feature Block?

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#163]
I don't see it on the page blocks page. I think they need it for the Events page. 

From Batch 1 comps:
![Screen Shot 2019-11-08 at 6 00 58 PM](https://user-images.githubusercontent.com/67819/68516349-c17ca780-0251-11ea-9244-8a01d2c36978.png)

**Comment by gracecanfield** [comment]
@mindywagner It should just be a Featured Content block, but only add one "feature". Feel free to reopen this if you're still not able to get it to work - was on my list to re-test this next week.
