### ISSUE TITLE
[Visual QA] About page

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#164]
**Desktop:**
The Leadership title needs more padding below it - currently at 30px. Let's bump to 50px.

**Comment by mindywagner** [comment]
If we're going with smaller headshots, I think we should go with the modal solution for this page. 

Comps:
![Team List](https://user-images.githubusercontent.com/67819/68516871-47e5b900-0253-11ea-91bf-5cd13c2f7a10.png)

![About - Bio Modal Circle](https://user-images.githubusercontent.com/67819/68516877-4a481300-0253-11ea-95bd-787e4a32c5e9.png)

**Comment by mindywagner** [comment]
We need to switch to the modal design for this one, per NPM's request.

**Comment by gracecanfield** [comment]
I think we left this as ambiguous with them - they'd previously mentioned that they wanted to see the bio lengths and that we might need to switch to modal. For the sake of prioritization (since it looks ok as-is), i'm closing this out.
