### ISSUE TITLE
[Visual QA] Adjust homepage hero to make their content work better

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#169]
Assuming that's the text NPM is sticking with, we should do the following:

Change main headline to 64px 
Change accompanying text to 18px
Change the width of the text box to 500px (currently 550px) - leave headline width as-is

NOTE: Would still highly recommend sticking with a shorter & bigger headline for this design

Result:
![Screen Shot 2019-11-11 at 10 04 21 AM](https://user-images.githubusercontent.com/67819/68597369-da13da00-046a-11ea-991d-9f6865899489.png)

**Comment by gracecanfield** [comment]
@mindywagner We got a request from NPM - could you provide updated guidance (edit your original issue description) to address this?

## Overview

**Page or Element Name**
homepage hero

**Example URL**
https://live-national-public-media-v2.pantheonsite.io/

**Related Trello card:**
https://trello.com/c/6T7LNQ2n
	
## Details

**Summary:**
We'd like the hero header and copy to not overlap with the image. It's hard to read on many photos.

**Current vs. Desired state:**
Currently the homepage hero header and copy overlap with the hero image. We'd like these fields to not overlap. Please left align the header with the NPM Logo.

**Screenshots**
![Screen_Shot_2019-11-22_at_11 02 09_AM](https://user-images.githubusercontent.com/6934226/69570901-d0bc5e80-0f8e-11ea-9cb7-2e4a83b72dc5.png)

![Screen_Shot_2019-11-22_at_11 02 16_AM](https://user-images.githubusercontent.com/6934226/69570916-d6b23f80-0f8e-11ea-9ee9-f3cb64e8c0a5.png)

**Comment by gracecanfield** [comment]
Side note: There was a separate request from NPM to make the headline/description rotate along with the text, so we should be keeping that in mind with this request.

**Comment by mindywagner** [comment]
New design is in Figma, in the Client Requested board.

![Hero](https://user-images.githubusercontent.com/67819/69659508-56521400-104c-11ea-8579-75ad22b323bb.jpg)

**Comment by gracecanfield** [comment]
@mindywagner Does this take into account tightened up spacing, or are we handling that separately?

**Comment by mindywagner** [comment]
Designs are in Figma, Client Request board

**Changes:**

- [ ] Headline - 88 -> 48px,; 120% line height, 20px padding between headline & subhead
- [ ] Subhead - 24px -> 18px (Intro style)
- [ ] WIdth of text - from 540px to 450px (7.5 cols out of 24)
- [ ] Padding between nav & image - 30px
- [ ] Padding between image & Pause button - 30px
- [ ] Add in pause/play functionality 
- [ ] Ideal world - we do some sort of fade transition on text/button & image to soften them up (rather than current slide from left to right) 

![Hero-1](https://user-images.githubusercontent.com/67819/69660066-86e67d80-104d-11ea-9eb0-d38820782067.jpg)
![Hero](https://user-images.githubusercontent.com/67819/69660067-86e67d80-104d-11ea-83c2-8d34285161e9.jpg)

**Comment by mindywagner** [comment]
@gracecanfield this takes into account tightened spacing. The spacing here is different from the global change, though, so I've noted the details in the task check list.

**Comment by gracecanfield** [comment]
@justinvandenberg Please be sure to make implementation changes based off of **Mindy's most recent comment** rather than the original ticket description!

**Comment by mindywagner** [comment]
**Mobile design:** 
![Mobile Homepage Hero](https://user-images.githubusercontent.com/67819/69761673-123b3e00-1136-11ea-863c-36b140281073.png)

@justinvandenberg note that I'm pulling the hero image in here. I think we should do this for all heros, as it will help with the fear that users may think the page is ending
