### ISSUE TITLE
Build-out styles for Podcast Sponsors & Promo Codes page

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#172]
Functionality:
>the plugin has been placed here: https://github.com/nationalpublicmedia/podcast-sponsors-plugin please let us know if you need anything else or have any questions. Thanks!

Comps:
Designed & available in Figma on the 404 & Sponsor Promote Page board

![Sponsors](https://user-images.githubusercontent.com/67819/68606640-dd17c600-047c-11ea-8874-e8c698d2e6a7.png)

**Comment by justinvandenberg** [comment]
@gracecanfield @mindywagner I don't think the "or" makes sense here. Looks like it's an "and".

**Comment by gracecanfield** [comment]
@justinvandenberg Sounds good!

**Comment by mindywagner** [comment]
Sorry - on the site they have OR, I didn't notice it wasn't correct

**Comment by justinvandenberg** [comment]
@gracecanfield this is on staging at https://live-national-public-media-v2.pantheonsite.io/podcast-sponsors/ Podcast Sponsors is a page and the actual sponsors are a custom post type. I've already entered all the ones they gave us and can go over some of the new stuff if you want when you're back.

**Comment by justinvandenberg** [comment]
Heads up, the "or" is gone because that's not actually how it was functioning.

**Comment by gracecanfield** [comment]
@justinvandenberg re: "the actual sponsors are a custom post type" - I'm confused, I thought they were keeping functionality as-is (data pulling from a spreadsheet rather than a structured custom post type in WP) and we were only doing styling?

**Comment by justinvandenberg** [comment]
@gracecanfield it still basically the same. We can hop on a call if you want a full rundown. Might be easier.
