### ISSUE TITLE
[Visual QA] Format template (audio) - Browse Products button

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#186]
Browse products button needs padding adjustment. 

**On desktop:**
There should be 50px from the last secondary card to the top of the Browse Products button, and 100px from the button bottom to the start of the next element. 
Current build:
![Screen Shot 2019-11-19 at 12 18 40 PM](https://user-images.githubusercontent.com/67819/69169668-beda4780-0ac6-11ea-9096-9d66af79371a.png)

**On mobile:**
There should be 30px from the last secondary card to the top of the Browse Products button, and 50px from the button bottom to the start of the next element. 

Current build:
![Screen Shot 2019-11-19 at 12 13 16 PM](https://user-images.githubusercontent.com/67819/69169774-ee894f80-0ac6-11ea-8c86-e3c7ed6da505.png)

**Comment by gracecanfield** [comment]
@mindywagner Is this still applicable, or n/a w/ other padding changes?

**Comment by mindywagner** [comment]
Looks like they've removed the Browse Products button, so... I guess it's set?
