### ISSUE TITLE
Implement Schema tags

### ISSUE THREAD

**Issue by jessicasheng15** [vigetlabs/npm#19]
Need to define schema tags with NPM.

**Comment by aakashtandel** [comment]
@jessicasheng15 I have two quick questions. 

1. Does NPM have a list of schema they want to use? https://schema.org/docs/full.html has a ton of options. Or are we adding the schema markup on our own, using our best judgement? 
2. Are we implementing this through Google Tag Manager or are we adding this directly to the site? We should probably do the latter or use something like SEOMatic (NPM is on Craft right?) to take care of adding the markup.

**Comment by gracecanfield** [comment]
@aakashtandel 

1. It's the latter - using our best judgment. NPM doesn't even know we're adding schema tags at this point.
2. Up to your recommendation.

**Comment by aakashtandel** [comment]
They're using Yoast on their current site so whoever is managing that plugin on their end may wonder how they do similar things on the new site. The best way to give them Yoast-like abilities is to use SEOMatic. If we aren't doing that, we should have basic schema markup on the page. Something like the following (with whatever their contact information is): 

```
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Organization",
  "url": "http://www.nationalpublicmedia.org",
  "name": "National Public Media",
  "contactPoint": {
    "@type": "ContactPoint",
    "telephone": "+1-555-555-5555",
    "contactType": "Customer service"
  }
}
</script>
```

Let's add that directly to the site instead of adding it through GTM.

**Comment by gracecanfield** [comment]
@aakashtandel We're using Yoast on this new site, too. Do you know where to add this? The admin is accessible in 1pw (under the "Live" site link `/wp-admin`).

**Comment by aakashtandel** [comment]
@gracecanfield Yoast creates schema markup on it's own, which I didn't know. ([Yoast documentation.](https://yoast.com/structured-data-schema-ultimate-guide/#how)) I haven't found a way to change the schema markup created by Yoast so if we want to add more bespoke schema markup, that will take some investigating. 

Here's a screenshot of the testing site's schema markup:
![Screen Shot 2019-11-06 at 9 17 38 AM](https://user-images.githubusercontent.com/8173223/68305910-83775c00-0076-11ea-8e3f-e04a8274d11a.png)

**Comment by gracecanfield** [comment]
Let's close this out, then - I think we're fine to use Yoast's for launch!
