### ISSUE TITLE
Troubleshoot slow page-load time (emphasis on mobile)

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#195]
## Overview

**Page Name & Example URL**
The entire site

**Describe the bug**
The site loads very slowly, on both wifi and cellular, on both mobile and desktop. On desktop, the images periodically load so slowly on the site. 

**Related Trello card:**
https://trello.com/c/dkF1SoTH

## Details

**To Reproduce**
It's not clear how to reproduce this. We have seen it periodically even when it's not the first tine loading a new site. On desktop it manifests itself as images loading very very slowly (5-10 seconds after the rest of the site). On mobile it shows blank areas on the entire sections of pages, including the navigation drop down.

**Expected vs. actual behavior**
We expect the site to load more quickly.

**Approach:**
We talked about you installing a WP caching plugin as a first step. If this doesn't help enough, we can look at lazy-loading on mobile or a third-party service like CloudFlare to help with image loading/performance.

**Screenshots**
n/a

**Desktop (please complete the following information):**
various computers and devices, and various browsers as well.

**Additional context**
We'd like additional information on data usage and compressing of images.

**Comment by gracecanfield** [comment]
@justinvandenberg I ran the site through Google's page speed test and they had a couple other suggestions for optiimizing load time (image converter, lazy loading plugin, and another tip about image sizing). Can your review as a part of this ticket?

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Flive-national-public-media-v2.pantheonsite.io

**Comment by justinvandenberg** [comment]
@gracecanfield I have a branch working with a `srcset` fix which should load more appropriate image sizes at smaller screens. It'd be nice to see how far that gets the site as well.

**Comment by justinvandenberg** [comment]
@gracecanfield I've added the Autoptimize plugin. It should handle image lazy-loading and optimization. Somehow the PageSpeed Insights score got a lot worse on mobile? 

@yaychris I'm getting this admin error after installing a new plugin - "Autoptimize cannot write to the cache directory (/srv/bindings/a1419e17d6ca457aa5e0ee68948dbe51/code/web/cache/autoptimize/), please fix to enable CSS/ JS optimization!" Can we change file permissions on Pantheon?

**Comment by gracecanfield** [comment]
@justinvandenberg Are there fixes in place on staging I should be looking at?

Staging is loading **very** slowly for me (it took about 20-30 seconds to even load https://test-national-public-media-v2.pantheonsite.io/page-blocks/ for the first time, though it loaded quickly on subsequent reloads). Same exact thing with the https://test-national-public-media-v2.pantheonsite.io/formats/audio/

I'm not experiencing this on production. Can you take a look at this and re-evaluate whatever changes have been made? If those are updated on staging now, it appears to have had a significant adverse affect rather than a positive affect.

**Comment by justinvandenberg** [comment]
@gracecanfield still have to get the permissions stuff addressed. The plugin I installed won't work without the right permissions on the file above. That plugin should handle image optimization and lazy-loading.

**Comment by gracecanfield** [comment]
@yaychris Can you help w/ this on Wednesday morning? We've told the client we can have these fixes in place by EOD Wed and need to have time to QA. Thanks!

**Comment by yaychris** [comment]
I believe I've fixed the issue in the dev environment. I don't see the error mentioned, and the main tab has a "Cache Info" section with the updated path and says it's writable.

The same fix will apply to other environments, once they're deployed.

I have a few other comments I will reply with in a bit.

**Comment by yaychris** [comment]
Additional notes:

* The plugin does image optimization via a third party service called "ShortPixel". Does NPM know this, and are they okay with it? The service is free for up to 100 images/month. Beyond that, it's paid. Again, do they know this?
* It seems like we're adding a lot of technology to resolve an issue that won't exist if those PNGs are just converted to JPEG. WEBP, srcsets, etc are fine and useful, but they aren't necessary to solve this problem, and they won't address the core problem.
* The client should be educated to use JPEGs, not PNGs (assuming they are the ones who uploaded them).

**Comment by gracecanfield** [comment]
Thanks! @justinvandenberg and I chatted and we're going to hold off on any additional plugin installations for now, and first are asking the NPM team to replace the PNGs with JPGs. [followed up w/ the client here](https://trello.com/c/dkF1SoTH/155-troubleshoot-slow-loading-time-mobile-emphasis-195#comment-5de850e7a251a73b7101f062)
