### ISSUE TITLE
Contact Us page form scrolls left and right

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#199]
## Overview

**Page Name & Example URL**
contact page: https://live-national-public-media-v2.pantheonsite.io/contact/

**Describe the bug**
the form on the contact us page scrolls from left to right and we cant figure out how to resolve this on our end. The same thing happens on mobile.

**Related Trello card:**
https://trello.com/c/ETwzInd1

## Details

**To Reproduce**
1. Go to contact page
2. hover your mouse over the entry form, and scroll from left to right (if you can)
3. See that some of the form moves to the left.

**Expected vs. actual behavior**
We expect the form to just remain static if a user accidentally scrolls.

**Desktop (please complete the following information):**
 - OS: macos, magic mouse
 - Browser chrome
 - Version Version 78.0.3904.70 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - OS: iOS 13.1.3
 - Browser chrome
 - Version ?

**Screenshots**
![358E4ABB-D79A-45BF-9CC4-B36C7734F443 (1)](https://user-images.githubusercontent.com/6934226/69571766-c13e1500-0f90-11ea-9e6a-e2c28420fdb2.png)
![Screen_Shot_2019-11-15_at_9 33 36_AM](https://user-images.githubusercontent.com/6934226/69571775-c602c900-0f90-11ea-971d-19bc5cdc8c23.png)

**Comment by gracecanfield** [comment]
@justinvandenberg Looks like the horizontal scroll is fixed, but I'm seeing a slight vertical scroll (on both large and smaller screen sizes). Is this something that you can fix before we ship this to production?

**Comment by justinvandenberg** [comment]
@gracecanfield we can't do anything simple because it's an iframe. We can adjust the pixel height in the WYSIWYG manually for now.

**Comment by gracecanfield** [comment]
Got it! Then let's consider this ready for prod.
