### ISSUE TITLE
Implement GZIP data compression of text-based assets

### ISSUE THREAD

**Issue by jessicasheng15** [vigetlabs/npm#20]

**Comment by jeremyfrank** [comment]
I think this might be a server thing or maybe .htaccess config on Pantheon. Docs say it should be enabled by default, but it isn't. https://pantheon.io/docs/guides/frontend-performance#gzip-compression Reassigning to @yaychris.

**Comment by yaychris** [comment]
It's enabled and working.

![DevTools - www nationalpublicmedia com: 2019-12-18 12-33-05](https://user-images.githubusercontent.com/13268/71109139-9f504080-2192-11ea-8119-7be8e9b97d8d.png)

**Comment by gracecanfield** [comment]
🎉
