### ISSUE TITLE
Header: Back & forth movement bug

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#200]
## Overview

**Page Name & Example URL**
Top Nav

**Describe the bug**
Nav bar moves up and down continuously for some reason...Not sure how to recreate this exactly, but it's happened for all of us multiple times.

 **Related Trello card:**
https://trello.com/c/RcQNORXm

## Details

**To Reproduce**
I'm sorry, i cant recreate this. But i think it has something to do with where my mouse is when it leaves the window.

**Expected vs. actual behavior**
We expect this bar to not move up and down inexplicably. 

**Screenshots**
Video to reproduce that Mindy took last week - https://www.dropbox.com/s/lvhl2067e5v5c4i/Screen%20Recording%202019-11-21%20at%2011.23.10%20AM.mov?dl=0

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome
 - Version 78.0.3904.70 (Official Build) (64-bit)

**Comment by mindywagner** [comment]
I'm not seeing this anywhere now - I think it's resolved.
