### ISSUE TITLE
Cards and scrolling elements should swipe on mobile

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#202]
## Overview

**Page Name & Example URL**
Program cards, testimonial scrollers (homepage and sponsorships), Product and research cards

**Describe the bug**
We expected the cards and scrolling elements to be swipeable on mobile.

**Related Trello card:**
https://trello.com/c/BgVIJ0qo

## Details

**To Reproduce**
1. Go to homepage on mobile
3. Scroll down to program cards
4. See that you cannot use your thumb to swipe the cards to the left.

**Expected vs. actual behavior**
we expected to be able to swipe all the cards and scrolling elements on mobile. currently, you have to click the left and right buttons.

**Screenshots**
If applicable, attach screenshots to help explain your problem. 

**Smartphone (please complete the following information):**
 - Device: iphone x
 - OS: 13.1.3
 - Browser chrome

**Additional context**

**Comment by gracecanfield** [comment]
>Carousels: Convert to use plugin (mobile swipe & easier fading functionality, lazy-load)

**Comment by haleyjohnso** [comment]
This works on my iPhone (8) and on browserstack (latest Galaxy, Pixel and iPhone X). I'm not sure which product and research cards share this behavior--I could only find the program cards and testimonials on the homepage.

Also, just visually verifying that the first testimonial card is supposed to have a dark bar across the top, unlike the rest of the cards:
<img width="273" alt="Screen Shot 2019-12-17 at 2 01 20 PM" src="https://user-images.githubusercontent.com/57419582/71035091-02c96800-20d8-11ea-8ba2-3ad942744666.png">
<img width="284" alt="Screen Shot 2019-12-17 at 2 01 09 PM" src="https://user-images.githubusercontent.com/57419582/71035115-0ceb6680-20d8-11ea-9d70-46f0a7b38840.png">

**Comment by haleyjohnso** [comment]
There seems to be not enough padding between the buttons on the testimonial arrows and the next section on the /podcast-sponsorship/ page

![IMG_4509](https://user-images.githubusercontent.com/57419582/71036149-52a92e80-20da-11ea-9523-655848260607.jpg)

**Comment by justinvandenberg** [comment]
@haleyjohnso care to check again on test please?

**Comment by haleyjohnso** [comment]
Padding and lines (lack thereof) look great!! Good to go
