### ISSUE TITLE
Header menu - admin: Unable to view "description" field for Platform sub-menu items

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#207]
## Overview

**Page or Element Name**
platforms subnav text

**Example URL**
n/a

**Related Trello card:**
https://trello.com/c/cuGLv8fw
	
## Details

**Question:**
How do we edit the platforms sub nav drop down? We cant locate the lorem ipsum language.

(NPM can't see the Description field, even when logged into an account with Administrator privledges. Can't figure out why that would be.)

**Screenshots:**
<img width="300" alt="Screen_Shot_2019-11-25_at_11 08 11_AM" src="https://user-images.githubusercontent.com/6934226/69574506-598ac880-0f96-11ea-9a24-8d466395a90c.png">

**Comment by justinvandenberg** [comment]
@gracecanfield looks like this is just hidden. You can reveal it by clicking "Screen Options" in the top right corner of the page. I believe it's user-based.
