### ISSUE TITLE
Report detail page: Admins can edit Hero CTA button text/link

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#209]
## Overview

**Page or Element Name**
Report page type

**Example URL**
Example: https://live-national-public-media-v2.pantheonsite.io/insights/reports/the-spoken-word-audio-report/

**Related Trello card:**
https://trello.com/c/QL2d3GQq
	
## Details

**Question:**
In the hero block on the Report detail page, The front-end logic looks for a PDF download uploaded to the CMS, and IF that is present, it includes the "Download the Report" button and links to the PDF.

NPM would instead like to have the ability to have the button link to the form at the bottom of the page, via an anchor link. Usually when we first release a report (such as the current Spoken Word Audio Report) we require users to fill out a form in order to download.

If there is another existing solution that makes that possible other than the anchor link one I described, we're open to that too.

**Screenshots:**
![Report-Page](https://user-images.githubusercontent.com/6934226/69575504-63153000-0f98-11ea-9ea3-4295d284ff8b.png)

**Comment by justinvandenberg** [comment]
@gracecanfield do you think we can get away with adding the ID `text`/`embed` to the block? They would only be able to link to the first instance of either block. Otherwise we'd need a more robust solution.
