### ISSUE TITLE
Product spec thumbnails: Users can expand images in modal

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#210]
## Overview

**Page or Element Name**
Samples on Products pages

**Example URL**
https://live-national-public-media-v2.pantheonsite.io/products/voice-landing-page/

**Related Trello card:**
https://trello.com/c/HjNNcMWz
	
## Details

**Summary:**
the product sample images are so small they are basically unusable. Can those please open to a larger image in the same modal that is used for the videos? We'd like them to be able to scroll between one another as well.

**Current vs. Desired state:**
Currently the product sample images are too small to see. We would like them to open on click to a larger modal window (similar to how the video currently opens). Additionally, the caption or description should be listed below the image in the modal window.

**Screenshots**

![Screen_Shot_2019-11-13_at_4 19 05_PM](https://user-images.githubusercontent.com/6934226/69581040-ca84ad00-0fa3-11ea-8a0c-7b4e723cfb0b.png)

**Comment by justinvandenberg** [comment]
@gracecanfield I recall discussing having a carousel or just the single image. Do you remember where we settled on that?

**Comment by gracecanfield** [comment]
@justinvandenberg Single image for launch.
