### ISSUE TITLE
make repo private?

### ISSUE THREAD

**Issue by olets** [vigetlabs/npm#212]
Happened to notice that this repo shows up at https://github.com/vigetlabs when I'm not logged in. Maybe it's on purpose so not messing with it myself

**Comment by gracecanfield** [comment]
@olets I don't think it should be private - but when I go to Settings, it looks like I can't make it private. @justinvandenberg Do you know why it wasn't private to begin with, and how to handle? (How do we normally handle privacy of forked repos?) ([screenshot](https://www.dropbox.com/s/8t93o16uwadaoc5/Screenshot%202019-12-02%2008.40.51.png?dl=0))

**Comment by justinvandenberg** [comment]
@gracecanfield @olets I think it has to be public because it's forked from NPM. I could be wrong though?

**Comment by olets** [comment]
Yes I see now that NPM's own repo is public. Forks of public repos are public. _Iff_ you wanted to make the convos private I think you can contact Github support and ask for the fork to be "detached" (have never tried but apparently GH is good with that request). Would require that we have push access to NPM's repo if NPM wants their own copy of the code
