### ISSUE TITLE
Add site favicon

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#214]

**Comment by gracecanfield** [comment]
@mindywagner Could you provide the file for this?

**Comment by mindywagner** [comment]
This was already provided at some point - here are the files. Note that I used the P because that's what they use now. 

[NPM Favicons.ico.zip](https://github.com/vigetlabs/npm/files/3917142/NPM.Favicons.ico.zip)

**Comment by ten1seven** [comment]
It was possible to upload this right in the admin (Appearance > Customize > Site Identity) so I uploaded the favicon for all environments.
