### ISSUE TITLE
[Visual QA] Services page hero text needs consistent padding

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#219]
Since we cut the feature card overlap elsewhere, we should cut it here as well - that should fix this padding issue. 

![Screen Shot 2019-12-03 at 11 05 28 AM](https://user-images.githubusercontent.com/67819/70068624-5b6c1180-15be-11ea-9166-43393c1fb5bb.png)

**Comment by justinvandenberg** [comment]
@mindywagner didn't we decide scrap that overlap and use the standard "Featured Content" block? If so, that section is just around for legacy data.

**Comment by mindywagner** [comment]
We decided to scrap the overlap and use the Featured Content blocks - but on the test site i'm still seeing an overlap. Are you saying they will need to put the content in differently?

**Comment by justinvandenberg** [comment]
@mindywagner I just left that there for legacy data @gracecanfield think I can add that current content to the normal blocks on staging then remove the old block?

**Comment by gracecanfield** [comment]
@justinvandenberg Looks like they are in fact using the featured content blog in terms of the real content on production: https://live-national-public-media-v2.pantheonsite.io/services/

They must have changed it somewhere along the line, so I think we should account for that content scenario instead of just changing staging.

**Comment by justinvandenberg** [comment]
@gracecanfield the one on production is a featured content block with the overlap. We moved away from that and to the one used elsewhere on the site. There'd be data loss with just those 2 blocks.  Does that make sense?

**Comment by justinvandenberg** [comment]
On staging the new block is below the old block https://test-national-public-media-v2.pantheonsite.io/services/

**Comment by gracecanfield** [comment]
@justinvandenberg Ah, ok! I didn't realize that getting rid of that extra feature block would solve the issue. Just did it myself https://test-national-public-media-v2.pantheonsite.io/services/. 

To be clear, are you saying on production there will be a data loss when we push this live, or can we effect the styling change without them having to re-enter content? No huge deal either way; just want to keep a list for myself of anything they'll need to re-enter content for.

**Comment by justinvandenberg** [comment]
@gracecanfield there will be data loss, but luckily that block was only used on that one page.

**Comment by gracecanfield** [comment]
@justinvandenberg Got it! Assuming no other work needs to be done on this, feel free to move this to "Ready for Client QA (On Staging)" then (I just created this column to help us keep track of those tickets that have passed internal QA but still need client QA on staging along w/ the padding stuff, before going to prod).
