### ISSUE TITLE
Services & Work index: Build-out & WP config

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#22]
### Overview

* **Page/Element:** Services & Work index page
* **URL:** `/services`
	
### Details

**Source files:**
* [Figma - Batch 3 - Format desktop & mobile comp](https://www.figma.com/file/NmTYeQFyu7XPlzTMSKFOzF/NPM-Comps---For-Buildout?node-id=852%3A3852)

**Tasks:**
* [ ] WP setup
* [ ] Build-out & wire-up

**Functional specifications:**

**A. CMS fields**
See "Services & Work Index" section of [data modeling airtable - Content Types & Fields tab](https://airtable.com/tblYGOMZcUp2WYox2/viwqDJ7kPQqzVkGKN?blocks=hide)

**B. Annotations**
See annotations and comments in Figma (linked above)

**C. Revisions in build**
* None! (everything should be reflected in zee comps)

**D. Comps**

![Services - Index](https://user-images.githubusercontent.com/6934226/66775369-cab46780-ee91-11e9-9470-f729ad6285e5.png)

![Mobile Services Index](https://user-images.githubusercontent.com/6934226/66775373-cbe59480-ee91-11e9-8387-3163bc5f9e77.png)

**Comment by justinvandenberg** [comment]
@gracecanfield this should just be a page with the `Services` template. The detail pages will be child pages.

**Comment by gracecanfield** [comment]
When I try to visit the Services index page I created in the admin, I get a blank screen: 
https://npm.staging.vigetx.com/services/

![Screen Shot 2019-10-25 at 8 28 15 AM](https://user-images.githubusercontent.com/6934226/67571219-68652d80-f701-11e9-8264-608d02c72ff9.png)
