### ISSUE TITLE
[Visual QA] Hero area eyebrows 

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#224]
For all level hero area eyebrows, update from 16px to 12px to adjust for text size changes and to be consistent with tertiary pages like product & work detail (since headline sizes are now consistent with them as well).

Buildout:
![Screen Shot 2019-12-03 at 11 06 57 AM](https://user-images.githubusercontent.com/67819/70071261-0bdc1480-15c3-11ea-9281-9115e94b6fe6.png)

Desired Result:
![Screen Shot 2019-12-03 at 12 14 45 PM](https://user-images.githubusercontent.com/67819/70073257-83f80980-15c6-11ea-9542-55a1d5902ccc.png)

**Comment by justinvandenberg** [comment]
@mindywagner should this be a global change for all the following headings? 
<img width="591" alt="Screen Shot 2019-12-03 at 12 12 11 PM" src="https://user-images.githubusercontent.com/8126358/70081632-2794ea00-15c6-11ea-8157-5ba715f4a39d.png">

**Comment by mindywagner** [comment]
Yes - thanks!
