### ISSUE TITLE
[Visual QA] Hero images - vertical spacing

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#227]
At the point where the overlap no longer occurs, is there a way for us to vertically center the images? They look odd/broken at these medium breakpoints b/c of the -50px spacing that remains on them. 

![Screen Shot 2019-12-03 at 11 59 04 AM](https://user-images.githubusercontent.com/67819/70072441-01bb1580-15c5-11ea-82ed-aca76fc8f3b6.png)
 
![Screen Shot 2019-12-03 at 12 02 18 PM](https://user-images.githubusercontent.com/67819/70072460-07b0f680-15c5-11ea-8f47-dc7c601f0c09.png)

**Comment by justinvandenberg** [comment]
@mindywagner this should be functioning differently on the test site. It should be effected by the full-height switch.

**Comment by mindywagner** [comment]
Ahhh, wrong site - sorry!
