### ISSUE TITLE
[Visual QA] Large blockquotes

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#228]
See this: https://github.com/vigetlabs/npm/issues/174

Also, they want us to take the font size down on these. 

Changes needed:
- [x] Make sure quotes center vertically within the green box
- [x] Take the large italic text down to 24px 

Buildout:
![Screen Shot 2019-12-03 at 12 09 33 PM](https://user-images.githubusercontent.com/67819/70072889-de449a80-15c5-11ea-8f2c-650101fc6ba6.png)

Desired result:
![Screen Shot 2019-12-03 at 12 09 58 PM](https://user-images.githubusercontent.com/67819/70072894-e0a6f480-15c5-11ea-9f85-521bd1f68389.png)

**Comment by mindywagner** [comment]
Two things:

- [ ] Getting a weird shadow cutoff effect, but only on some quotes in the carousel. 

![Screen Shot 2019-12-04 at 11 14 31 AM](https://user-images.githubusercontent.com/67819/70159810-81111d80-1687-11ea-9673-900666de9979.png)

To replicate: 
https://test-national-public-media-v2.pantheonsite.io/sponsorship/podcast-sponsorship/
Check out slides 2 & 3 with a wider browser window (~1100 and up seems to do it)
___________

- [ ] Doesn't look like the mobile padding was adjusted for this element - I think we want 25px top and bottom padding (currently looking like 50)

Buildout:
![Screen Shot 2019-12-04 at 11 18 30 AM](https://user-images.githubusercontent.com/67819/70160036-d2b9a800-1687-11ea-9b1f-ace51de0a6c4.png)

Updated:
![Screen Shot 2019-12-04 at 11 17 55 AM](https://user-images.githubusercontent.com/67819/70159989-c46b8c00-1687-11ea-8b6d-5aaf122823ae.png)

**Comment by justinvandenberg** [comment]
@mindywagner would it be possible to use 30px for padding. The current shadow has a 30px spread (blur? offset?). Then we wouldn't have to worry about any cutoff.

**Comment by mindywagner** [comment]
Yep, that fix makes sense to me (or taking blur down to 25)
