### ISSUE TITLE
[Visual QA] Play button needs shadow

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#229]
Buildout:
![Screen Shot 2019-12-03 at 12 12 40 PM](https://user-images.githubusercontent.com/67819/70073293-93775280-15c6-11ea-98ba-527add95d236.png)

Design:
![Screen Shot 2019-12-03 at 12 15 59 PM](https://user-images.githubusercontent.com/67819/70073339-ae49c700-15c6-11ea-8d3b-459b41f43c4b.png)

**Comment by justinvandenberg** [comment]
@mindywagner can you re-check this one. This should have been added after the FED pairing.

**Comment by mindywagner** [comment]
Doesn't appear to be implemented for the play buttons over video:

![Screen Shot 2019-12-06 at 4 32 25 PM](https://user-images.githubusercontent.com/67819/70357915-135f2000-1846-11ea-91e5-47a31eabdd37.png)

![Screen Shot 2019-12-06 at 4 32 23 PM](https://user-images.githubusercontent.com/67819/70357918-15c17a00-1846-11ea-9fe6-9c1ba4bb0a02.png)
