### ISSUE TITLE
[Visual QA] Program card - awkward breakpoint transition

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#237]
At about 639px-529px the program card logo doesn't scale properly with the card. 
 
![Screen Shot 2019-12-05 at 5 02 29 PM](https://user-images.githubusercontent.com/67819/70278730-cfefad80-1782-11ea-9e72-8a029ccb4dac.png)

**Comment by jeremyfrank** [comment]
@mindywagner Can you re-test? I can't replicate the issue.

**Comment by mindywagner** [comment]
This must have been fixed last week. Closing out!
