### ISSUE TITLE
Photo Credits

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#238]
Add photo credits to:

- [x] Hero block
- [x] Featured image block
- [x] Image block
- [x] Homepage quote/image block

**Details:**
10px #fff text with a 40px tall gradient behind them - see Figma Pre-Launch board for examples

![Photo Credit Treatment](https://user-images.githubusercontent.com/67819/70332019-aaa88100-180e-11ea-928b-97c0130423ed.png)

**Comment by gracecanfield** [comment]
Additional fix:
* [ ] Add image captions back to image block
* [ ] Confirm whether captions are working on videos

**Comment by justinvandenberg** [comment]
@mindywagner @gracecanfield I'm not able to add the credit to the images added in a WYSIWYG. We do have the captions working on that. Also, the "Description" field is the one the credit pulls from.

**Comment by gracecanfield** [comment]
@justinvandenberg Thanks! Can you remind me the context/use case for adding images in a WYSIWYG? (I thought we were just accounting for the image block itself + those other blocks)

**Comment by gracecanfield** [comment]
@justinvandenberg QA fixes. Please deploy to production after these are done:

See https://test-national-public-media-v2.pantheonsite.io/page-blocks/

* [ ] Descriptions aren't displaying on image blocks exception when multiple images are being used together ([screenshot of image block with and without text](https://www.dropbox.com/s/cqyx2l8g6g9z5fa/Screenshot%202019-12-06%2017.08.37.png?dl=0), not showing description as expected)
* [ ] Descriptions aren't displaying on featured content blocks ([screenshot](https://www.dropbox.com/s/i99648zqv3nd8n9/Screenshot%202019-12-06%2017.07.43.png?dl=0), [screenshot](https://www.dropbox.com/s/rh2x4rxgbbuuv13/Screenshot%202019-12-06%2017.07.55.png?dl=0), [screenshot](https://www.dropbox.com/s/l0df3c2w6h6cavm/Screenshot%202019-12-06%2017.08.17.png?dl=0)
* [ ] Homepage quote block - image isn't displaying ([screenshot](https://www.dropbox.com/s/d294u7ih0p2meu4/Screenshot%202019-12-06%2017.09.53.png?dl=0) - https://test-national-public-media-v2.pantheonsite.io/

**Comment by gracecanfield** [comment]
@justinvandenberg Image blocks still aren't displaying captions.

https://live-national-public-media-v2.pantheonsite.io/page-blocks/

([screenshot of current on prod](https://www.dropbox.com/s/9rbznztqlf5rrut/Screenshot%202019-12-09%2010.00.26.png?dl=0))
