### ISSUE TITLE
Products index: Build-out & WP config

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#24]
### Overview

* **Page/Element:** Product index page
* **URL:** `/products`
	
### Details

**Source files:**
* [Figma - Format desktop & mobile comp](https://www.figma.com/file/NmTYeQFyu7XPlzTMSKFOzF/NPM-Comps---For-Buildout?node-id=728%3A25372)

**Tasks:**
* [ ] WP setup
* [ ] Build-out & wire-up

**Functional specifications:**

**A. CMS fields**
See "Product Index" section of [data modeling airtable - Content Types & Fields tab](https://airtable.com/tblYGOMZcUp2WYox2/viwqDJ7kPQqzVkGKN?blocks=hide)

**B. Annotations**
See annotations and comments in Figma (linked above)

**C. Revisions in build**
* Note that mobile comp may not reflect design revisions based on client feedback. Refer to the desktop comp for final patterns/design and use mobile comp just as a guide for how things should stack responsively.

**D. Comps**

![Product - Detail](https://user-images.githubusercontent.com/6934226/66759381-27059000-ee6e-11e9-8699-35ab54267bb6.jpg)

![Product - Detail](https://user-images.githubusercontent.com/6934226/66759386-2967ea00-ee6e-11e9-8641-206c190993d2.png)

**Comment by gracecanfield** [comment]
@justinvandenberg Forgot to include a reminder in here that we need to be able to direct-link to filtered states of the product index page.

**Comment by justinvandenberg** [comment]
@gracecanfield Platforms are a taxonomy under Products. Should appear on the sidebar of the products. I'll work on the rewrite for the URL. By default WP taxonomy archives are singular.

**Comment by gracecanfield** [comment]
@justinvandenberg Currently, I can't access the products index page. When I go to https://npm.staging.vigetx.com/product, I get this error message: 

![Screen Shot 2019-10-25 at 8 00 55 AM](https://user-images.githubusercontent.com/6934226/67569728-a3fdf880-f6fd-11e9-917d-f257501742da.png)

When I go to https://npm.staging.vigetx.com/products, I get this error message:

![Screen Shot 2019-10-25 at 8 01 16 AM](https://user-images.githubusercontent.com/6934226/67569731-a6f8e900-f6fd-11e9-9638-f64f941ee341.png)
