### ISSUE TITLE
Fix easing on Program Carousel

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#243]
The animation seems to be jerky again - looks like we need to soften the easing on it. 

Try adding `ease-out` or `ease-in-out` and perhaps `transform: translate3d(0, 0, 0);`

https://www.nationalpublicmedia.com/

Program carousel screenshot:
https://www.dropbox.com/s/tw0jc5yirshw9yq/Screenshot%202019-12-16%2013.58.40.png?dl=0

**Comment by jeremyfrank** [comment]
Mindy, looks like Justin redid the carousel sliders and this doesn't apply anymore. Can you review and confirm?

**Comment by mindywagner** [comment]
The easing looks like it was taken care of, but wondering if we could quickly fade the one that disappears to the far left as it's disappearing - to help it look less abrupt

**Comment by jeremyfrank** [comment]
@justinvandenberg mind if I reassign this to you since you are familiar with the new carousel slider implementation?

**Comment by justinvandenberg** [comment]
@jeremyfrank yup!

**Comment by haleyjohnso** [comment]
looks so much smoother!
