### ISSUE TITLE
Audience carousel jumps w/ content length

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#244]
We should make the height of this block locked to the longest content, similar to blockquotes. 

https://live-national-public-media-v2.pantheonsite.io/audience/

**Comment by jeremyfrank** [comment]
@mindywagner Which block is this? I don't see a carousel on this page.

**Comment by mindywagner** [comment]
This is what I'm thinking of - not sure what to call it. Vertical tabs?

![Screen Shot 2019-12-18 at 12 36 39 PM](https://user-images.githubusercontent.com/67819/71109378-0e2d9980-2193-11ea-8d07-e2197a91d64e.png)

**Comment by jeremyfrank** [comment]
LOE for that would be kind of high. I don't think that it would be worth the time. Thoughts?

**Comment by mindywagner** [comment]
Yeah, let's not worry about it then. Closing!
