### ISSUE TITLE
Podcast Sponsors: URL Update

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#252]
**Current:**
https://live-national-public-media-v2.pantheonsite.io/podcast-sponsors/

**Desired:**
Please change the URL (and all sub-URLs like https://live-national-public-media-v2.pantheonsite.io/podcastsponsors/allsongsconsidered/) to be https://live-national-public-media-v2.pantheonsite.io/podcastsponsors/

**Comment by ten1seven** [comment]
What you're wanting here is for there to be no deep linking to specific podcast sponsors?

**Comment by gracecanfield** [comment]
@ten1seven Nope - we just need to remove the dash from between the word `podcast` and `sponsors` - `podcastsponsors` instead of `podcast-sponsors`

**Comment by ten1seven** [comment]
This was a page slug that can (and already was) handled through the admin.

![Screen Shot 2019-12-09 at 3 06 58 PM](https://user-images.githubusercontent.com/137020/70468742-a3df6f80-1a95-11ea-8ac2-363b886de976.png)

**Comment by gracecanfield** [comment]
@ten1seven There is actually a bug here that is different than the original issue contents. See steps to reproduce below.

## Overview

**Page Name & Example URL**
https://live-national-public-media-v2.pantheonsite.io/podcastsponsors/

**Describe the bug**
The podcast sponsors link changed to match the other naming convention of the site, but there are many hard-coded links from the NPR site pointing here, and we need to have this changed back.

## Details

**To Reproduce**
Steps to reproduce the behavior:
1. Go to https://live-national-public-media-v2.pantheonsite.io/podcastsponsors/
2. Click on the drop down to select any show.
3. click your curser into the top URL bar, and then type Enter.
4. See how the URL changes to be /podcast-sponsors/.

**Expected vs. actual behavior**
We'd like this link to stay at /podcastsponsors/ without the dash.
**Screenshots**
If applicable, attach screenshots to help explain your problem.
