### ISSUE TITLE
Podcast Sponsors: Functional QA issues (filtering not displaying results as expected)

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#259]
Justin refactored the code and it appears to have created incorrect results during filtered states. 

It should behave exactly as the old site did in terms of functionality. However, the results aren't pulling in the same number of results based on filters entered. Some examples:

* [ ] Expected: If you filter by Hidden Brain on the old site, you'll see 15 results. https://www.nationalpublicmedia.com/podcastsponsors/hiddenbrain/
  * Actual: On desktop, filter by Hidden Brain on the new site - https://live-national-public-media-v2.pantheonsite.io/podcastsponsors/hiddenbrain/. You'll see 5 results. 
  * Actual: On mobile, if I filter by Hidden Brain I see 2 results. ([screenshot](https://www.dropbox.com/s/styz2tocghsy96a/IMG_5461.PNG?dl=0))
* [ ] Expected: If you filter by Ask Me Another on the old site, you'll see 15 results. https://www.nationalpublicmedia.com/podcastsponsors/askmeanother/ 
  * Actual: On desktop, filter by Ask Me Anoter on the new site - https://live-national-public-media-v2.pantheonsite.io/podcastsponsors/askmeanother/. You'll see 1 result. 
  * Actual: On mobile (iPhone X/Safari), if I filter by Ask Me Another I see no results ([screenshot](https://www.dropbox.com/s/tnkrjfozfbs4egt/IMG_5460.PNG?dl=0))

**Comment by gracecanfield** [comment]
Spreadsheet:
https://docs.google.com/spreadsheets/d/1qXS-NVRzDh2o398w7279IlDPFtOCgPR9kH3aCjZJeoA/edit#gid=0

Changes Justin made when he refactored:
• All things are tracked in the URL now (keywords, podcasts, hasOffers)
• Plugin only returns data (rather than also returning template)
• jQuery is removed
• Added by post type instead of pages
• More dynamic (URL changes based on keyword in addition to filter selected, I think?)
• More performant

**Comment by gracecanfield** [comment]
From Francis:

>if it helps, here's a diff of the changes i made when troubleshooting the issue. It may not be the most optimal but it will help illustrate the source of the problem. >https://gist.github.com/fndaru/9722bff1d848fa99f0593bc038ec281e

**Comment by gracecanfield** [comment]
**QA fixes needed**

* [ ] **Account for periods**
* check out results for https://live-national-public-media-v2.pantheonsite.io/podcastsponsors/alt-latino/ (no results) vs. https://www.nationalpublicmedia.com/podcastsponsors/alt-latino/

* [ ] **Account for ellipses**
* check out https://live-national-public-media-v2.pantheonsite.io/podcastsponsors/wait-wait-dont-tell-me/ (no results) vs. https://www.nationalpublicmedia.com/podcastsponsors/waitwaitdonttellme/

* [ ] **URL points to a 404 when page is refreshed or when direct linked to a filtered state**
* Visit any URL with a filtered state, like https://live-national-public-media-v2.pantheonsite.io/podcastsponsors/all-songs-considered/
* Expected: I'm taken to filtered state of the page
* Actual: I get a 404
* Same thing happens if I go to https://live-national-public-media-v2.pantheonsite.io/podcastsponsors, then select a podcast filter (URL changes as expected), and then hit refresh on the page.

**Comment by justinvandenberg** [comment]
@gracecanfield is it ok if I close this?
