### ISSUE TITLE
[Browser QA] Quote block: add padding beneath arrows

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#264]
There should be padding beneath the arrows in the quote block on mobile. (check w/ Mindy if you need specific guidance on px).

Tested on an iPhone X running Safari.

![IMG_5462](https://user-images.githubusercontent.com/6934226/70489966-259dc000-1acb-11ea-9140-961df4624b66.PNG)

**Comment by jeremyfrank** [comment]
@gracecanfield Can you share a link to a page that has one?

**Comment by gracecanfield** [comment]
@jeremyfrank I think this actually just got fixed by Justin in another change he was working on this week! Closing out.
