### ISSUE TITLE
[Visual QA] Homepage hero - mobile - add padding

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#269]
- [x] Add 20px of margin before the "Join the conversation." headline. 
- [x] Make mobile P margin bottom 20px instead of 30px (global update)

Buildout:
![Screen Shot 2019-12-10 at 12 13 44 PM](https://user-images.githubusercontent.com/67819/70552169-d5fcda00-1b46-11ea-9c4e-cef88144ce82.png)

Desired result:
![Screen Shot 2019-12-10 at 12 16 36 PM](https://user-images.githubusercontent.com/67819/70552245-f75dc600-1b46-11ea-8dde-bef387d90d13.png)

Mobile body copy styles from [Figma](https://www.figma.com/file/NmTYeQFyu7XPlzTMSKFOzF/NPM-Comps-For-Buildout?node-id=795%3A119):

![Screen Shot 2019-12-10 at 12 20 02 PM](https://user-images.githubusercontent.com/67819/70552616-b619e600-1b47-11ea-9147-b5c00c49ea16.png)
![Screen Shot 2019-12-10 at 12 22 49 PM](https://user-images.githubusercontent.com/67819/70552730-eb263880-1b47-11ea-804d-cffc66c9c2f2.png)
![Screen Shot 2019-12-10 at 12 23 26 PM](https://user-images.githubusercontent.com/67819/70552734-eceffc00-1b47-11ea-8707-e646370f8d5d.png)

**Comment by jeremyfrank** [comment]
> Make mobile P margin bottom 20px instead of 30px (global update)

Looks like that 30px bottom margin is also applying to other block level elements (dl, ol, ul, blockquote, img) as well as a wp class (.wp-caption): https://github.com/vigetlabs/npm/blob/master/web/themes/npm/assets/styles/elements/text.css#L10-L22

Should those also be reduced to 20px, or just the paragraph?

**Comment by mindywagner** [comment]
Let's make it for the p, dl, and ol

Leave IMG, blockquote, and caption as-is - they'll need a bit more breathing room

Thanks!
