### ISSUE TITLE
Product Detail Pages: Links for Product variants

### ISSUE THREAD

**Issue by haleyjohnso** [vigetlabs/npm#276]
## Overview

**Page or Element Name**
Product Detail pages

**Example URL**
https://www.nationalpublicmedia.com/products/audio-interstitial/

**Estimate**
2
	
## Details

**Summary:**
Create individual links for each product variant so that each tab/variant has its own unique URL

**Current vs. Desired state:**
Currently, anchor links exist for each tab, but do not appear in the URL automatically as a user navigates the site. Anchor links also take users directly to the tab area of the page, and the main nav obscures the tab labels.
Desired state: We would like to discuss having the URL change when users navigate between tabs. 
We are ok with anchors (#) for the links. Two desired results:
1) Link changes in URL bar when users click through tabs
2) Tabs are visible on screen when user goes directly to an anchor link. see example for what it's currently doing, hiding behind the nav bar.

**Screenshots**
![Screen_Shot_2019-12-13_at_9 05 54_AM](https://user-images.githubusercontent.com/57419582/70824366-561d7c80-1d9f-11ea-97c3-af71d74af017.png)

**Blocker**
Need to determine whether we'd like to change anchor-linking functionality to updating the URL using a different method

**Comment by gracecanfield** [comment]
@justinvandenberg FYI - we accidentally closed this ticket (my mistake) - reopening it because it is still a thing that needs to be done this week

**Comment by gracecanfield** [comment]
@justinvandenberg Is there an easy way to make this so that the tab also changes when the user navigates back?

**Comment by gracecanfield** [comment]
@justinvandenberg it also looks like # 2 above was never resolved:

>Tabs are visible on screen when user goes directly to an anchor link. see example for what it's currently doing, hiding behind the nav bar.

I'm reproducing this myself on staging. Can we either make the anchor a bit above where the tab actually starts to account for the sticky nav obstructing the view, OR can we just have the anchor link make the corresponding tab be selected, but not actually jump the user down to that point on the page? cc: @haleyjohnso

**Comment by haleyjohnso** [comment]
Hey @justinvandenberg -- We're good on Chrome and Safari, but Firefox is still wonky I think:
https://test-national-public-media-v2.pantheonsite.io/products/audio-interstitial/#npr-player---desktop

![Screen Shot 2019-12-20 at 3 24 51 PM](https://user-images.githubusercontent.com/57419582/71296447-ebd77f80-233c-11ea-8132-ab5c37983b7b.png)

**Comment by justinvandenberg** [comment]
@haleyjohnso I'm not able to reproduce on Firefox. Maybe it's cached the page?

**Comment by haleyjohnso** [comment]
@justinvandenberg aha, cleared cache on Firefox and no longer an issue. 
However, can you make sure these aren't getting clipped on mobile? (This can obviously wait until Monday)
I tried
https://test-national-public-media-v2.pantheonsite.io/products/brand-soundscapes/#soundscape-75
on browserstack (Pixel 4, Chrome)
<img width="268" alt="Screen Shot 2019-12-20 at 8 33 55 PM" src="https://user-images.githubusercontent.com/57419582/71302450-3fab8e00-2368-11ea-8cd4-4c5381d007d1.png">


and saw that the tab was getting clipped (far right)

**Comment by justinvandenberg** [comment]
@haleyjohnso the tabs should be scrollable on mobile.

**Comment by haleyjohnso** [comment]
@justinvandenberg 

<img width="952" alt="Skip_to_Content" src="https://user-images.githubusercontent.com/57419582/71379855-8f6d9d80-2592-11ea-9daa-7073db73ea91.png">
- [ ] Skip to Content is still visible on Internet Explorer (NPM)
- [ ] I'm still seeing the tabs hiding behind the nav on the latest version of Edge

**Comment by haleyjohnso** [comment]
fyi, for our records, this is resolved on IE but Edge needs a ticket

**Comment by gracecanfield** [comment]
@haleyjohnso I believe this went out before Christmas, right? (aside from the edge issue captured separately.) If so, could you close out this ticket? (It's currently still under "Up Next")

**Comment by gracecanfield** [comment]
@haleyjohnso Does this have any additional work needed or is it good to close out?

**Comment by haleyjohnso** [comment]
Good to close! I've already let Whitney know on trello @gracecanfield
