### ISSUE TITLE
Meta titles not displaying as defined in Yoast

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#278]
It appears that all pages have the title tage `National Public Media`, even if something different has been specified for that page in Yoast.

**Steps to Reproduce:**
1. Visit https://www.nationalpublicmedia.com/programs/. You'll see that the title tag is `National Public Media`. 
2. Visit https://www.nationalpublicmedia.com/wp/wp-admin/post.php?post=371&action=edit. You'll see that the SEO title is set in Yoast to be `Title` `Page` `Separator` `Site title`.

It looks like this is the case for all pages (see screenshot below).

Could you fix?

![Screen Shot 2019-12-13 at 1 32 25 PM](https://user-images.githubusercontent.com/6934226/70824969-63dbfd80-1db1-11ea-8625-a518dd176cf3.png)

**Comment by haleyjohnso** [comment]
I'm now seeing [Name of Page] | National Public Media as the title tag. For example, /programs/ has a title tag of National Public Media | Programs, which seems to be consistent for what's in Yoast.
<img width="418" alt="Screen Shot 2019-12-16 at 4 39 26 PM" src="https://user-images.githubusercontent.com/57419582/70952306-15ce3080-2023-11ea-911c-f8b9d3c19623.png">

**Comment by haleyjohnso** [comment]
Grace, assigning you but I think this issue is good to close!

**Comment by gracecanfield** [comment]
@justinvandenberg Moved this to ready for production, but it's fine to hold off until the rest of this week's changes are client-approved.
