### ISSUE TITLE
[QA] Font fix (global)

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#28]
For some reason, we have Mindy's intro text defined as italicized in build, but it shouldn't be italicized. See screenshot with Figma on the left, build-out (staging) on the right. Refer to Master Components > Intro text style in Figma. This is an issue I've noticed globally across the site. 

https://www.dropbox.com/s/maxzepgbacf3fpg/Screenshot%202019-10-18%2008.35.50.png?dl=0

**Comment by gracecanfield** [comment]
@justinvandenberg I'm still seeing this issue - take a look at https://npm.staging.vigetx.com/.

I did a hard refresh too. Could it be a caching thing?

**Comment by justinvandenberg** [comment]
@gracecanfield this is in the admin. The text in the field was set to italic.

**Comment by gracecanfield** [comment]
🤦‍♀ Sorry, I should have checked the admin. Didn't even think of it because I didn't do it manually...maybe it somehow got transferred over when copy/pasting...
