### ISSUE TITLE
Make work and article images clickable

### ISSUE THREAD

**Issue by haleyjohnso** [vigetlabs/npm#280]
## Overview

**Page or Element Name**

Work and article samples

**Example URL**
https://live-national-public-media-v2.pantheonsite.io/insights/
https://live-national-public-media-v2.pantheonsite.io/services/

**Estimate**
0.5
	
## Details

**Summary:**
Our user testing is proving that a lot of people try to click on the images of either the articles or work details samples to try to navigate to the work detail page or article. 

**Current vs. Desired state:**
Currently, the only way to navigate to the work details page or insights article is to click the View the work/'Read More' links. We'd like the images to also be links to the work details pages and articles.

**Screenshots**
![Screen_Shot_2019-11-15_at_11 36 33_AM](https://user-images.githubusercontent.com/57419582/70825913-d09bcb80-1da2-11ea-9d14-78bb21f9e25d.png)
--
![Screen_Shot_2019-11-15_at_11 37 46_AM](https://user-images.githubusercontent.com/57419582/70825921-d2658f00-1da2-11ea-99a3-a148374df4a3.png)

**Comment by justinvandenberg** [comment]
@haleyjohnso should I add clickable images to the Featured Content blocks as well? It's a pretty similar setup.

**Comment by haleyjohnso** [comment]
hey @justinvandenberg sorry I didn't catch your note yesterday until just now. When you say Featured Content blocks, do you mean the larger ones near the top of these pages? like this one:
<img width="1330" alt="Screen Shot 2019-12-18 at 11 01 35 AM" src="https://user-images.githubusercontent.com/57419582/71111070-d2d89e00-2185-11ea-95bd-02efdefa0686.png">
 
Beyond that, the requested images are clickable! Looks good

**Comment by justinvandenberg** [comment]
@haleyjohnso correct. There's a couple different instances of them across the site.

**Comment by haleyjohnso** [comment]
@gracecanfield did you have an opinion about making some of the larger images clickable? I think my only hesitation is how that translates on mobile or a tablet (where accidental click may make it annoying).

**Comment by gracecanfield** [comment]
@haleyjohnso I think your point is a great one about accidental clicks on mobile. I'd vote for not making those larger images clickable, and sticking with our current implementation.
