### ISSUE TITLE
Make audio play buttons larger on mobile

### ISSUE THREAD

**Issue by haleyjohnso** [vigetlabs/npm#282]
## Overview

**Page or Element Name**
Audio on work details pages

**Example URL**
https://live-national-public-media-v2.pantheonsite.io/work/homeinstead/

**Estimate**
1
	
## Details

**Summary:**
audio play buttons are very small for a mobile user

**Current vs. Desired state:**
the control buttons on the mobile samples in work pages are too small, please increase their size.

**Screenshots**
![0BA9DF0C-0221-4F4C-AD3D-AE1CB0808965](https://user-images.githubusercontent.com/57419582/70827285-2625a780-1da6-11ea-8296-db2b5d00632a.png)

**Comment by mindywagner** [comment]
Here's a design solution for mobile - found in Figma here: https://www.figma.com/file/NmTYeQFyu7XPlzTMSKFOzF/NPM-Comps-For-Buildout?node-id=3686%3A29326

![audio player thumbnail](https://user-images.githubusercontent.com/67819/70932823-9e8ba300-2008-11ea-947d-509d0033661b.png)

**Comment by haleyjohnso** [comment]
The buttons are definitely bigger on mobile (iPhone 8, Safari), although I have small-ish fingers, so I'd double check with the client. Still need to test this on android.

**Comment by mindywagner** [comment]
Just as an FYI to the client - the hit space is designed to be 40x40px, which is pretty standard for mobile.

**Comment by haleyjohnso** [comment]
Good on android!
