### ISSUE TITLE
Services details pages: add more block options

### ISSUE THREAD

**Issue by haleyjohnso** [vigetlabs/npm#283]
## Overview

**Page or Element Name**
Services single template

**Example URL**
https://www.nationalpublicmedia.com/services/audio-visual-design/
	
## Details

**Summary:**
Please add more block options to the templates: 

-Related products
-featured content blocks.

**Current vs. Desired state:**
currently blocks are not available to add.

**Comment by justinvandenberg** [comment]
@haleyjohnso is this the block you're referring to as  Related Products
<img width="622" alt="Screen Shot 2019-12-17 at 1 41 22 PM" src="https://user-images.githubusercontent.com/8126358/71032662-08707f00-20d3-11ea-8d4f-968264430fd6.png">
?

**Comment by gracecanfield** [comment]
@justinvandenberg Correct!

**Comment by haleyjohnso** [comment]
I'm able to add the Related Products and Featured Content blocks to the example page, services/audio-visual-design/.
@justinvandenberg, did you add this to all pages? Just curious if I should test more.

**Comment by justinvandenberg** [comment]
@haleyjohnso just that one template.

**Comment by haleyjohnso** [comment]
Cool, then this is good to go!
