### ISSUE TITLE
Add thumbnail option for images on product samples

### ISSUE THREAD

**Issue by haleyjohnso** [vigetlabs/npm#284]
## Overview

**Page or Element Name**

**Example URL**
https://www.nationalpublicmedia.com/products/brand-soundscapes/#npr-player-brand-soundscape

**Estimate**
1
	
## Details

**Summary:**
Please add a separate thumbnail option for images on products specs pages. We have decided to use logos for the thumbnails on videos and audio, and would like to create consistency and be able to add them to images as well.

**Current vs. Desired state:**
currently, images for spec samples on products page only show a small version of the image, we'd like them to allow a separate image to place a sponsor's logo in the thumbnail.

**Screenshots**
<img width="1197" alt="Screen_Shot_2019-12-12_at_1 37 31_PM" src="https://user-images.githubusercontent.com/57419582/70827653-ef03c600-1da6-11ea-8b88-48b9bea06f4e.png">

**Comment by justinvandenberg** [comment]
@gracecanfield there are 2 options for this, either will need some data entry or reentry. 

1.  Add a new full-size image field. This will maintain all the current audio and video thumbnails, but will need all the image thumbnails (assuming they want new ones) and modal images entered. 
2. Keep the image field as the modal image and add a new thumbnail image field. This will keep all the modal images, but will need all audio, video, and image thumbnails entered. 

What do you think?

**Comment by gracecanfield** [comment]
@justinvandenberg I think option 1 seems like it'll require less re-entry, right? (having to re-enter only image content vs. all audio/video/image thumbnails? If so, let's do option 1.)

**Comment by justinvandenberg** [comment]
@gracecanfield that's what I was thinking too!

**Comment by haleyjohnso** [comment]
Confirmed, I'm seeing the option to add either an image or a thumbnail

**Comment by gracecanfield** [comment]
**OPEN TASKS:**

**Today, ASAP:** 
* [ ] @justinvandenberg to separate out front-end functionality into its own branch, but deploy the new image field changes (WP only) to staging for QA
* [ ] After ☝️ is complete, Grace or @haleyjohnso to QA after that is done (depending on who has time first)

**Next Week:**
* [ ] @haleyjohnso to coordinate with Justin next week to get the front-end functionality branch on staging next week (_after we deploy all the other changes to prod_) to finish QA (verify that the new full-size image field is updating the correct place on the front-end, and same with the thumbnail?)

**Comment by haleyjohnso** [comment]
hey @justinvandenberg let me know if I'm testing this incorrectly, but I'm not seeing the new image come through. 

Page:  https://test-national-public-media-v2.pantheonsite.io/products/center-stage/ 

I'm testing on the homepage center stage section, where the image on the left is the thumbnail:
![Screen Shot 2019-12-20 at 2 47 40 PM](https://user-images.githubusercontent.com/57419582/71295202-33a7d800-2338-11ea-9cae-83cb051e4b72.png)

On the admin side, I add a random image from their media library into the corresponding image field. The point is to make it different than the thumbnail so that I can tell it's working.

Here's what I get (and I did do a hard refresh):
![Screen Shot 2019-12-20 at 2 49 47 PM](https://user-images.githubusercontent.com/57419582/71295280-78337380-2338-11ea-800a-ab18a9362726.png)

_Also_ wondering about the Skip to Content button in the screenshot in the upper left--is that supposed to be there? I have not been tabbing around or using VO.

**Comment by justinvandenberg** [comment]
@haleyjohnso that's what we want to happen right now. We're going to let them enter the content then push the front-end change after that's entered. 

The skip to content button should not be there. I think @jeremyfrank did something with that recently?

**Comment by haleyjohnso** [comment]
Ah okay--is there any other way that I should test this @gracecanfield if I can't visually verify if it's working?

I know the Skip to Content button was visually missing from my a11y QA--and still was, last time I checked.

**Comment by justinvandenberg** [comment]
Looks like it was addressed in this PR https://github.com/vigetlabs/npm/pull/301

**Comment by justinvandenberg** [comment]
@haleyjohnso take a gander again. I pushed up a hotfix for the Skip to Content button.

**Comment by haleyjohnso** [comment]
@justinvandenberg looks good--I'm not seeing the Skip to Content button

**Comment by haleyjohnso** [comment]
hey @justinvandenberg I wanted to verify that this page https://test-national-public-media-v2.pantheonsite.io/products/broadcast-credit-national/ **shouldn't** have the new image field on the admin side because each thumbnail has audio associated with it. Is that right?

**Comment by justinvandenberg** [comment]
@haleyjohnso that is correct. It should only appear when Type field is set to Image.

**Comment by justinvandenberg** [comment]
@haleyjohnso @gracecanfield the front-end image swap should be on staging now.
