### ISSUE TITLE
Product redirects with hashes

### ISSUE THREAD

**Issue by justinvandenberg** [vigetlabs/npm#287]
https://trello.com/c/Vsf2br9Y/187-redirect-links-with-anchor-tagshttps://github.com/vigetlabs/npm/issues/287

**Comment by justinvandenberg** [comment]
@gracecanfield there should be a "Hash" field on the side of all projects admin pages. That's where the hash for the redirect is set up. I'll set up the main redirect in the admin now.

**Comment by haleyjohnso** [comment]
I see the hash field on the products admin pages and I successfully tested the functionality with https://test-national-public-media-v2.pantheonsite.io/products/pre-roll#15preroll.

I also tested it by adding a new hash to a product page.

I then removed the new hash from the product page, and found that the URL still worked. Other product URLs with hashes work always, so that even a random string after the hash will result in the product page that proceeds the hash. Is that how it's supposed to work?

**Comment by justinvandenberg** [comment]
@haleyjohnso do you mean that if the has doesn't match any of the products all of them show?

**Comment by haleyjohnso** [comment]
@justinvandenberg I might not be understanding the purpose of the hashes. I realized I could append any hash that I wanted to the the end of the URL and it wouldn't change the page content. The hashes are for redirects, right?

**Comment by gracecanfield** [comment]
@haleyjohnso Correct! See the [trello card linked in the original ticket description](https://trello.com/c/Vsf2br9Y) for details. NPM attached a screenshot of a redirect that wasn't working before - `/products/npr-podcasts/#15preroll`. The goal would be for them to be able to set that up as a redirect that points to that page's new URL on the new site - `/products/pre-roll`.

But, @justinvandenberg With the changes you made, could you clarify the exact steps that we and NPM should take to get these working in the admin? (It's not totally clear to me whether the redirect plugin should be used at all for these, or not.)

**Comment by haleyjohnso** [comment]
Yeah, seconded what Grace said. I see that redirects are working, but maybe not as they are supposed to?

For example: https://www.nationalpublicmedia.com/products/npr-org/#nprplayer
aka
https://test-national-public-media-v2.pantheonsite.io/products/npr-org/#nprplayer

is supposed to redirect to (according to the redirect spreadsheet):

https://test-national-public-media-v2.pantheonsite.io/products/audio-interstitial/

but instead it redirects to:

https://test-national-public-media-v2.pantheonsite.io/products/?platforms=desktop-display,display#nprplayer

**Comment by justinvandenberg** [comment]
@gracecanfield @haleyjohnso I misinterpreted the original ask. Right now, it's going to a filtered view instead of the product detail page which Haley pointed out. I think the code I have can still work, I just need to tweak some things.

**Comment by justinvandenberg** [comment]
@haleyjohnso @gracecanfield is this working as expected now? If it is, i'll add support for multiple hashes  https://dev-national-public-media-v2.pantheonsite.io/products/#30midroll

**Comment by haleyjohnso** [comment]
hey @justinvandenberg can confirm that https://dev-national-public-media-v2.pantheonsite.io/products/#30midroll redirects as expected! Not seeing successful redirects yet for other URLs but I bet you need to add them

**Comment by gracecanfield** [comment]
@justinvandenberg Could you give a step by step list of exactly what NPM should do if they want to set up a new redirect that includes an anchor?

**Comment by justinvandenberg** [comment]
@gracecanfield they just have to add the appropriate hashes to the product it's supposed to redirect to. Below all 3 of those correspond to the mid-roll product. There's also some brief instructions above the field.
<img width="1260" alt="_NPM__SEO_Checklist__Metadata____Redirects_Worksheet_-_Google_Sheets" src="https://user-images.githubusercontent.com/8126358/71211463-6be1e480-226c-11ea-99f5-5bbe7e0440be.png">
<img width="1437" alt="Edit_Product_‹_National_Public_Media_—_WordPress-2" src="https://user-images.githubusercontent.com/8126358/71211469-6f756b80-226c-11ea-9058-59693ef915ea.png">

**Comment by haleyjohnso** [comment]
I tried adding the hash 15postroll to the Postroll product page. Instead of the original URL redirecting to the /post-roll/ page, it redirected to https://test-national-public-media-v2.pantheonsite.io/products/?platforms=podcasts-audio,audio#15postroll

Am I misunderstanding how to test this? 

Also, when I went to remove the postroll15 hash and update the page, I got this error message on the admin side. There was no hash entered previously.
<img width="284" alt="Screen Shot 2019-12-19 at 4 28 40 PM" src="https://user-images.githubusercontent.com/57419582/71217909-b66b5d00-227c-11ea-9b14-564dd5dbb7af.png">

**Comment by justinvandenberg** [comment]
@haleyjohnso I removed one of their redirects and added the new one (must have come down in the db clone on one of the recent deploys). https://test-national-public-media-v2.pantheonsite.io/products/npr-podcasts/#postroll15 should work now (you may have to incognito it). I can make the hash field not required, unless we want them to set up a redirect for each?

**Comment by haleyjohnso** [comment]
@justinvandenberg Okay, that also works as expected. 
Do we anticipate any of the other redirects will have issues? I don't want to have you keep fixing things that maybe they entered incorrectly.

I think I would make the has field not required, right? Not every page has a redirect, or does it?

**Comment by justinvandenberg** [comment]
@haleyjohnso I'll just have to make a note that we have to check their redirects after (maybe before because they're not working correctly now) the prod push. I'm not sure if every product is accounted for, but I just thought of new ones. I should definitely make that not required.

**Comment by gracecanfield** [comment]
**Open tasks:**
* [ ] @justinvandenberg Make `hash` field optional.
* [ ] @justinvandenberg As soon as we deploy to production, remove the original post-roll product page redirect set up in the redirects plugin

(@haleyjohnso you're correct that not every product might have a hash. Justin also noted to me that the post roll redirect issue is the only one that we've seen, so this shouldn't be an issue elsewhere.)

**Comment by haleyjohnso** [comment]
Hey @justinvandenberg - I've been testing a few of those redirects in the spreadsheet. I think I found a new one that doesn't work. 

https://test-national-public-media-v2.pantheonsite.io/products/npr-org/#story-center-stage 

redirects to

https://test-national-public-media-v2.pantheonsite.io/products/?platforms=desktop-display,display#story-center-stage

instead of https://test-national-public-media-v2.pantheonsite.io/products/center-stage/

**Comment by justinvandenberg** [comment]
@haleyjohnso looks like it's another one of the redirects they had entered. I wonder if we should reach out to them to make sure we're not missing anything? I've disabled that one for now.
<img width="290" alt="Screen Shot 2019-12-20 at 4 49 30 PM" src="https://user-images.githubusercontent.com/8126358/71299112-da947000-2348-11ea-9784-dd8c6ba42421.png">

**Comment by haleyjohnso** [comment]
@justinvandenberg is the first line in the screenshot how they entered the redirect?

**Comment by haleyjohnso** [comment]
@justinvandenberg I'll plan to flag that as part of the testing on Monday. What do we need to get from them in case we're missing something?

**Comment by justinvandenberg** [comment]
I think "Do you need `/products/npr-podcasts/` and `/products/npr-org/` (without a hash) to redirect to the filtered products page?" will suffice.

**Comment by gracecanfield** [comment]
@haleyjohnso Can this be closed out? (I believe this may have been in the batch o' tickets that went live around Christmas time?) If so, please feel free to close.
