### ISSUE TITLE
[Visual QA] Individual Article Page - LEFTOVERS

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#289]
### **Desktop & Mobile**

- [x] Blockquote element should have 30px margin/padding above the text and 30px margin/padding below the pink accent line. Right now it has 30px above and 0px below. [Buildout image](https://user-images.githubusercontent.com/67819/70940287-fda4e400-2017-11ea-8f86-5f0b0c4a9847.png) 

### **Desktop:**
- [x]  Hero image bottom padding needs adjustment. There's a few layers of padding happening here, so I'm not sure where to adjust it, but there should only be 50px between the hero and the next element. [Buildout image](https://user-images.githubusercontent.com/67819/70940252-eebe3180-2017-11ea-80b7-eac4ca32da2c.gif) 
- [x]  h5 - was designed to give them a section label style. Is this possible? If not, make the h5 16px bold. [Design comp](https://user-images.githubusercontent.com/67819/69076857-588bf100-0a02-11ea-8a7e-f6dcf75c0993.png)  |   [Buildout](https://user-images.githubusercontent.com/67819/70940489-6f7d2d80-2018-11ea-8456-f41f21c2c211.png)
 
###  **Mobile:** 
- ~[ ]  **Hero area:** Reduce top padding/margin above Insights eyebrow to 20px (currently 30) - this should apply to all mobile hero areas/page titles~
- ~[ ]  **Hero area:** Reduce bottom padding/margin on title area to 20px (currently 30), so it's closer to the hero image~
- [x]  **Hero area:** Hero image bottom padding/margin needs adjustment. There's a few layers of padding/margin happening here, so I'm not sure where to adjust it, but there should only be 30px between the hero and the next element. [Buildout image](https://user-images.githubusercontent.com/67819/70940708-e5819480-2018-11ea-9b77-d0445fa2ab5a.png) 
- [x]  Blockquote - Same padding fixes to desktop- spacing between text & blockquote should be 30px top & bottom on mobile [Buildout image](Screen Shot 2019-12-16 at 3 33 02 PM" src="https://user-images.githubusercontent.com/67819/70940972-75274300-2019-11ea-88be-9cf976cedb2f.png)

**Comment by jeremyfrank** [comment]
Turns out h5 and h6 styles were getting stripped out entirely.

Right side shows the styles applied (plus 16px as requested). Is this correct?

![image](https://user-images.githubusercontent.com/283397/71032792-14187180-20e4-11ea-889f-b05c8c122be8.png)

**Comment by gracecanfield** [comment]
@mindywagner Could you weigh in on @jeremyfrank 's question [here](https://github.com/vigetlabs/npm/issues/289#issuecomment-566741326)?

**Comment by mindywagner** [comment]
@jeremyfrank can we just make the h5 12px (leaving everything else the same)? Then we should be good to go. Thanks!
