### ISSUE TITLE
Play videos inline on small screens

### ISSUE THREAD

**Issue by haleyjohnso** [vigetlabs/npm#314]
## Overview

**Page or Element Name**
Videos on mobile

**Example URL**
Example: https://www.nationalpublicmedia.com/work/target/

**Time Estimate**
4

**Related Trello Card**
https://trello.com/c/vkko5DxX/209-suppress-video-modals-on-mobile-314

**Related Github issue**
Originally mentioned in #308 
	
## Details

**Summary:** On mobile modals, when a user clicks into a video modal on mobile, it actually displays _smaller_ than the inline thumbnail. The original purpose of the modal was to display the content in a larger format, but it's doing the opposite on mobile.

**Desired state:**
Suppress video modals on mobile.

**Screenshots**
N/A

**Comment by ten1seven** [comment]
FYI, the solution I chose here was to go with the native Vimeo or YouTube player interface on screens below 768px. Since it's much more difficult to trigger one of these types of videos to play from a custom button (consider that the current implementation isn't able to start the video playing when the modal opens when it's able to on desktop), I opted for the easier route of using the native interface that will allow 1-click playback rather than 2-click playback and a lot more code with the custom button.

**Comment by haleyjohnso** [comment]
Noted!

**Comment by haleyjohnso** [comment]
Hi @ten1seven how much more work would it be for you to exclude videos on the Spec Details section for all product pages https://www.nationalpublicmedia.com/products/custom-channel/#npr-one-custom-channel

Whitney's reasoning is that the videos are too small to read if inline (see below) and using a modal for those videos would be consistent with how they're using the audio clips in Spec Details as well. 

<img width="491" alt="Screen Shot 2020-07-01 at 10 16 27 AM" src="https://user-images.githubusercontent.com/57419582/86267490-04deaa00-bb84-11ea-8a5b-f0abc7d5c521.png">

**Comment by ten1seven** [comment]
Estimate: 2 hours

It's probably worth mentioning that rotating a phone to horizontal or using the full-screen control on the video is going to give someone a better viewing experience than a modal.

**Comment by haleyjohnso** [comment]
Confirmed--let's go with that estimate and implement that change.

**Comment by ten1seven** [comment]
@haleyjohnso this update is now on staging to review. I believe that the only other place videos like this are used is on the work pages. You can verify that they behave differently (as expected).

Product page with specs video (should always play in modal):
https://npm.staging.vigetx.com/products/custom-channel/

Work page with videos (should play in modal on large screens and inline on small screens):
https://npm.staging.vigetx.com/work/chipotle/

**Comment by haleyjohnso** [comment]
These look good to me. Notifying NPM for client QA.

**Comment by haleyjohnso** [comment]
Client confirmed that this is ready for production!
