### ISSUE TITLE
Merge CSS into main file

### ISSUE THREAD

**Issue by haleyjohnso** [vigetlabs/npm#329]
### Overview

- **Size:** 0.5
- **Level of urgency:** [High]
- **Potential deadline:** [6/19]
- **Harvest task:** National Public Media [NPM] > [01] Redesign & Support

**Page or Element Name**
Additional CSS file

**Example URL**
n/a
	
## Details

**Summary:**
We added some CSS into the additional css of the theme, and would like this to be formally added to the file to avoid any conflicts in class names. The css has been annotated and includes the reason/function it provides, but we can assist in testing this if preferred.

**Screenshots**
![Screen_Shot_2019-12-17_at_10 23 08_AM](https://user-images.githubusercontent.com/57419582/84174180-7fac1d80-aa3b-11ea-931a-82b4eee8f26e.png)

**Comment by haleyjohnso** [comment]
I see this on the brand soundscapes page as well as the Customizing Additional CSS sidebar. Let me know if there's a different way I should be QA-ing this, @ten1seven

**Comment by ten1seven** [comment]
I'm not aware myself, but this was rolled into the global styles so they will be on any page that needs them.
