### ISSUE TITLE
Work pages hero image / audio breaks on medium break point

### ISSUE THREAD

**Issue by haleyjohnso** [vigetlabs/npm#333]
## Overview
 
- **Level of urgency:** [Medium]
- **Size:** 2
- **Potential deadline:** [6/19]
- **Harvest task:** National Public Media [NPM] > [01] Redesign & Support

**Page Name & Example URL**
work details https://www.nationalpublicmedia.com/work/lagunitas/

**Describe the bug**
viewing the site at medium breakpoint (tablet) causes an audio player to float over the hero image, and also for the audio players to disappear from the audio section further down the page.

## Details

**To Reproduce**
1. Go to https://www.nationalpublicmedia.com/work/lagunitas/
2. Reduce your window size to a medium breakpoint (1046 × 922)
3. See that audio player floats over hero image, and audio player areas below are blank.

**Expected vs. actual behavior**
We expect the audio players to stay in their page block, and for no audio to appear over the hero image in medium break point.

**Screenshots**
![image (3)](https://user-images.githubusercontent.com/57419582/84177469-25618b80-aa40-11ea-9a0f-b00007d2a0e2.png)
![image (4)](https://user-images.githubusercontent.com/57419582/84177476-27c3e580-aa40-11ea-88d5-4016e384c209.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 79.0.3945.88 (Official Build) (64-bit)

**Comment by haleyjohnso** [comment]
hey @ten1seven - on IE11, the audio waves don't appear. We're not going to fix, right? I think I remember seeing it in previous QA but can't find a reference 
![Screen Shot 2020-06-16 at 6 23 07 PM](https://user-images.githubusercontent.com/57419582/84841094-9aaffc00-affe-11ea-9a83-49baaede31e1.png)

**Comment by ten1seven** [comment]
Correct, this is a big enough issue with IE11 that we decided not to try to fix.
