### ISSUE TITLE
PHP error

### ISSUE THREAD

**Issue by haleyjohnso** [vigetlabs/npm#338]
### Overview

- **Size:** 2
- **Level of urgency:** [Low]
- **Potential deadline:** [6/19]
- **Harvest task:** National Public Media [NPM] > [01] Redesign & Support

### Details

_Saw this in Pantheon... what is it?_
![image (6)](https://user-images.githubusercontent.com/57419582/84311603-cd4e8600-ab20-11ea-8ae6-ec285ab2ccd4.png)

**Comment by ten1seven** [comment]
I'm not seeing this error at this time.

![CleanShot 2020-06-15 at 16 13 48](https://user-images.githubusercontent.com/137020/84711311-3cfab180-af23-11ea-926c-16bab68b401b.png)

**Comment by haleyjohnso** [comment]
Same--I let Whitney know

**Comment by haleyjohnso** [comment]
No longer an issue--closing for now
