### ISSUE TITLE
Ability to edit hyperlink on buttons on Product pages

### ISSUE THREAD

**Issue by ten1seven** [vigetlabs/npm#349]
## Overview

**Page or Element Name**
Product Pages - Spec Download area under Spec Groups

**Example URL**
https://www.nationalpublicmedia.com/products/center-stage/
	
## Details

**Summary:**
Allow for Spec Download button to link to any URL, not just a PDF file.

**Current vs. Desired state:**
Currently the spec download button only lets an editor choose a PDF from the media library. We are changing spec docs to be Google Slides instead of PDFs, so will need these spec download buttons on the site to link to external URLs. Request is to change this editing interface to include a field to add an external URL instead of choosing a PDF file. 

https://trello.com/c/DgNyyE8p/220-ability-to-edit-hyperlink-on-buttons-on-product-pages

**Comment by ten1seven** [comment]
This is the new Specs/Guidelines UI. It's on staging for review.

![CleanShot 2020-06-23 at 13 28 05](https://user-images.githubusercontent.com/137020/85449871-7780d180-b555-11ea-9725-073bc756b88a.gif)

**Comment by haleyjohnso** [comment]
Tested! Works great. I'm going to move this to NPM review.
