### ISSUE TITLE
Text with Callout block: Build-out & WP config

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#36]
### Overview

* **Page/Element:** Text with callout block
	
### Details

**Source files:**
* [Figma - basic page elements](https://www.figma.com/file/NmTYeQFyu7XPlzTMSKFOzF/NPM-Comps---For-Buildout?node-id=1329%3A37913)

**Tasks:**
* [ ] WP setup
* [ ] Build-out & wire-up

**Functional specifications:**

**A. CMS fields**
See "Page blocks" section of [data modeling airtable - Content Types & Fields tab](https://airtable.com/tbljc70sgRwYWsS7k/viwcPzoIGM97kqc1V?blocks=hide)

**B. Comps**

![Screen Shot 2019-10-22 at 5 16 54 PM](https://user-images.githubusercontent.com/6934226/67334202-c4586800-f4ef-11e9-83a6-75e7d2cd3970.png)

**Comment by justinvandenberg** [comment]
@gracecanfield this is in the text block now. Use the megaphone icon.
