### ISSUE TITLE
[Analytics] Contact Us Form Submission, Audio Video plays, and Download Events

### ISSUE THREAD

**Issue by aakashtandel** [vigetlabs/npm#46]
Let me know if you have any comments or suggestions!

## Contact Us
Please fire the following code, once a user has successfully submitted a Contact Us form submission: 

![Screen Shot 2019-10-25 at 9 59 54 AM](https://user-images.githubusercontent.com/8173223/67577572-b6ccf900-f70e-11e9-9790-6736fcd3b218.png)

```
<script>
  window.dataLayer = window.dataLayer || [];
  dataLayer.push({
    'event': 'Contact Us Form Submission' ,
    'platform': 'SELECTED PLATFORM(S)' ,
    'scope': 'SELECTED SCOPE' 
  });
</script>
```

Dynamically replace the platform and scope. If the user selects more than one platform–such as NPR On Air and NPR Events–add both platforms, delimited by a comma. 

## Audio and Video Plays
Please fire the following code when a user plays a case study audio or video demo:

![Screen Shot 2019-11-01 at 11 29 32 AM](https://user-images.githubusercontent.com/8173223/68044345-886e9100-fcad-11e9-837d-b3800c30ad3e.png)

```
<script>
  window.dataLayer = window.dataLayer || [];
  dataLayer.push({
    'event': 'dataLayer push event' ,
    'event_category': 'AUDIO/VIDEO', 
    'event_action': 'TITLE', 
    'event_label': 'Play'
  });
</script>
```
Dynamically replace event category with “Audio” or “Video,” depending on element. Dynamically replace event action with the actual title of the media played. 

## Download Specs and Guidelines
Please add the following inline data attribute to the download specifications or content guidelines: 

![Screen Shot 2019-11-01 at 11 36 56 AM](https://user-images.githubusercontent.com/8173223/68044428-b18f2180-fcad-11e9-9dc9-7011e6329b9e.png)

```
data-track-gtm="Download|SPECS/CREATIVE CONTENT|CONTENT TITLE"
```
Dynamically replace event audio with the type of download, either “Specs” or “Creative Content Guidelines.” Dynamically replace event level with the actual title of the content downloaded.

**Comment by justinvandenberg** [comment]
@aakashtandel you can test the Contact Us form at https://live-national-public-media-v2.pantheonsite.io/contact/. I had to do it through Pardot, I'm not 100% sure it's going to work.

**Comment by aakashtandel** [comment]
@justinvandenberg This worked! Thanks for figuring that out. I've made the necessary changes to the NPM GTM to account for the Pardot form.

**Comment by aakashtandel** [comment]
Actually I missed the Audio/Video plays. I'm only seeing the dataLayer push event happen on the first play of a page. If a user clicks on the play button on a subsequent audio/video clip, the event is not triggered. 

Also, I'm seeing filler text for the event_action, but I'm assuming the audio/video title isn't being generated on the staging site. 

![Screen Shot 2019-12-02 at 4 29 20 PM](https://user-images.githubusercontent.com/8173223/69996904-03cb9880-1521-11ea-8ad3-96c68a0808f7.png)

Let me know if you have any questions.

**Comment by justinvandenberg** [comment]
@aakashtandel the audio title is pulled from the admin. If it doesn't exist it should default to "Audio/Video Title". Should we default to the filename? Could the events having the same title cause the other issue? The function fires on each play.

**Comment by aakashtandel** [comment]
@justinvandenberg Just to recap what we talked about yesterday. Let's go with using the dataLayer push event to show video plays (to account for both YouTube and Vimeo). 

Dynamically replace the title of the video. If there is no title, default to "Title Unknown". 
```
<script>
  window.dataLayer = window.dataLayer || [];
  dataLayer.push({
    'event': 'dataLayer push event' ,
    'event_category': 'Vide', 
    'event_action': 'TITLE', 
    'event_label': 'Play'
  });
</script>
```

Let me know if you need anything on this item. Slack me for a faster response.

**Comment by justinvandenberg** [comment]
@aakashtandel do you have time to check this on https://test-national-public-media-v2.pantheonsite.io/ this morning?

**Comment by aakashtandel** [comment]
Looks great on staging. Feel free to push to prod.
