### ISSUE TITLE
Get Started page: Build-out & WP config

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#47]
[Grace to add deets]

**Comment by justinvandenberg** [comment]
@gracecanfield I created a page for this under Pages in the admin.

**Comment by gracecanfield** [comment]
**QA fixes needed:**
* [ ] There should be an "Our Offices" title above the locations listed in the gray sidebar. (see [comp](https://www.dropbox.com/s/kr8lomutp31gf5f/Screenshot%202019-10-31%2016.21.58.png?dl=0)).
* [ ] There should be a thin gray line above the footer. ([comp screenshot](https://www.dropbox.com/s/y4j7nxsf23a8gd7/Screenshot%202019-10-31%2016.22.31.png?dl=0))

**Comment by justinvandenberg** [comment]
@gracecanfield I think they'll have to use the divider to add the line before the footer as its not a global element. Also, the "Contact Us" title will persist after submission. Is that ok?

**Comment by gracecanfield** [comment]
@justinvandenberg Isn't the divider a global element in cases where there's not a colored-background CTA directly above the footer? cc: @mindywagner 

>Also, the "Contact Us" title will persist after submission. Is that ok?

Yep, that's ok.

**Comment by gracecanfield** [comment]
**Low Priority:**
* [ ] There should be a thin gray line beneath the header on pages that start w/ a white background (Contact Us) ([comp screenshot](https://www.dropbox.com/s/ghkl2sufdkk3fc2/Screenshot%202019-11-01%2008.49.27.png?dl=0))

**Comment by mindywagner** [comment]
@gracecanfield yep - the divider should show on pages where the footer doesn't end with a full color block like the big footer callouts. Anytime it transitions white background element to white background footer, there should be a divider.
