### ISSUE TITLE
Pardot template: Build-out & WP config

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#51]
Please be sure to think through whether we need to have a separate page for confirmation, in order to track form submissions in GA/GTM. (This is a requirement.)

**Comment by justinvandenberg** [comment]
@gracecanfield this is on live now. There's a few things I couldn't get 100% the same but it's pretty close given the restrictions. https://live-national-public-media-v2.pantheonsite.io/get-started/
