### ISSUE TITLE
[Visual QA] Global Header - Dropdown

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#57]
1) Icons aren't displaying next to Formats.

2) **The dropdown should collapse if you click outside of the dropdown - say, if you click on the page below it. Right now it stays open until you select another page.** 

3. White & Blue versions: Can we add a subtle transition, like a fade, to make the appearance of the dropdown less abrupt? Mindy can come up with an example if needed. 

4) White & Blue versions: Add a hover state to the links under Audio - these text links should have an underline on hover.   

5) White & Blue versions: Add a hover state to the Subheads (Audio, Display, etc.) - text underline, similar to the top items but closer to the text so we don't make the dropdown too much taller (Mindy can mock up if needed)

6) White & Blue versions: Hover state needed for button. The Contact button on dark header should swap to filled blue (#0A6EB9) with white text on hover (basically reversed out) The Contact button on light header should swap to filled darker red (#C22A49) with white text. Styles added in the Styles Figma board & Justin has been tagged in a comment there.

7. White & Blue versions: Platform icons are missing

**Comment by justinvandenberg** [comment]
@gracecanfield the icons are enter in the admin. Appearance -> Menus -> Menu Item -> Image.

**Comment by mindywagner** [comment]
Looks fantastic! The only thing I noticed is that this is still not working as expected: 

**The dropdown should collapse if you click outside of the dropdown - say, if you click on the page below it. Right now it stays open until you select another page.**

**Comment by justinvandenberg** [comment]
@mindywagner whoops, I didn't actually mean to move this. I was waiting until QA was complete from NPM because I knew it was on their list.

**Comment by gracecanfield** [comment]
Closing this - all items seem N/A from what i can tell.
