### ISSUE TITLE
[Visual QA] Program Card Carousel

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#60]
1) The card motion feels slow - guessing a quicker transition and some in/out easing would help that feel more natural
2) Program cards should always be the same height - we should have a max character length
3) Program tile images look very blurry - is it compressing too much? 
4) Blue Show Details link should show an underline on hover
5) Arrow buttons need a hover state (shown in Styles board under Components section). Dark blue swaps to light blue #65BDFF.
6) When you are on the first card and cannot go <, that arrow should use the "unselectable" state shown in Styles / Components
7) The arrow navigation should be further to the left. Try 30px from the left (until it goes to center on smaller breakpoints)
8) For all links that have an arrow at the end - the arrow should go at the end of the text, even if that text wraps. Also the arrow shouldn't scale (right now it gets smaller as you size down the browser before the 1st breakpoint) (I wrote a separate ticket for this since it's global)
8) Learn more button isn't on the cards when flipped
9) The "tucked under" shadow isn't visible on the far right side of the carousel. See comp.
10) Cards should have a hover state - on hover, they should grow slightly larger (5-10%?) and their shadow should deepen. See Styles / Components for details.
11) I think we decided the entire card would be clickable to get to the backside, correct? 
12) The View All Programs button should have a hover state to darker red. See Styles/Base System/Buttons in Figma.

**Comment by gracecanfield** [comment]
@justinvandenberg These client requests came in - can you confirm whether they're accounted for with the changes you made for this ticket, or should I enter a different issue? 

* [ ] Make See Details link location consistent on all cards
* [ ] Move scrolling buttons to left side under first card
* [ ] See All Programs linked below cards near scrolling buttons
* [ ] This essentially becomes moot when we [change the max width of the site](https://trello.com/c/Qc9dmurg), but the program cards are too large at the largest viewport size (1920x1080)
