### ISSUE TITLE
Visual QA: Featured Content block

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#61]
* [x] I don't think NPM should have control over text styles here.
* [ ] Let's change "Button text" and "Button link" to "CTA text" and "CTA link" (field labels) since it's a text link on the front end.
* [x] I think we can make the breakpoint for swapping from 2 cards to 1 a bit lower. Maybe 800-850px instead of ~1000px? 
* [x] On text links that have the arrow treatment, can we make the arrow slide to the right a few pixels on hover, so that there's a 2nd visual indication it's a link?

**Comment by justinvandenberg** [comment]
The link fields are cloned from a global field group. I can't change the labels.
