### ISSUE TITLE
Related Insights block: Polish

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#62]
Example staging URL: https://npm.staging.vigetx.com/formats/audio/

* [ ] Why is there both a “Featured Image AND an “Image” field? (I see that “Image” is pulling into the Insight block, but then what is the “Featured Image” used for? Seems like we could get rid of it.)
* [x] There should be a “View All” button underneath the articles that links to Insights index page
* [x] Should say “Article” or “Report”, depending on what type the article is.

![Screen Shot 2019-10-30 at 6 17 46 PM](https://user-images.githubusercontent.com/6934226/67903316-9b645280-fb41-11e9-99b5-786f758870f3.png)

**Comment by justinvandenberg** [comment]
Featured Image is used for the Featured Insight block. It's cropped at a different aspect ratio than the Image field.
