### ISSUE TITLE
[Visual QA] CTA block: Polish

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#63]
* [ ] Blue background - should have white button with pink text, not blue outlined button ([screenshot figma on left, staging on right](https://www.dropbox.com/s/y8t8wgohefwfs3q/Screenshot%202019-10-18%2012.45.15.png?dl=0)

**Comment by justinvandenberg** [comment]
@gracecanfield the image one should have a white button per the comps. 
![Screen Shot 2019-11-07 at 4 52 49 PM](https://user-images.githubusercontent.com/8126358/68437769-23201180-017f-11ea-8e2f-62f8d391e1b3.png)
