### ISSUE TITLE
[QA] Resources footer links on mobile

### ISSUE THREAD

**Issue by jessicasheng15** [vigetlabs/npm#65]
This may be expected functionality, in which case we can close this ticket.

I was testing the general responsiveness of the footer and see that the alignment is just slightly off from the comps. The links look too left-justified.

*Currently:*
![image](https://user-images.githubusercontent.com/36860796/67974000-f0f33a80-fbe7-11e9-8097-669b5b1f88c8.png)

*Comp*
![image](https://user-images.githubusercontent.com/36860796/67974190-5ba47600-fbe8-11e9-8b33-781c3150c454.png)

**Comment by gracecanfield** [comment]
Great catch!

**Comment by jessicasheng15** [comment]
@justinvandenberg this looks better! However, I think the center alignment of the Resources links are just a little off. I tried to draw out where the misalignment is -- I'd expect to see the same padding to the left and right of both columns, but it looks left-justified.

Feel free to ping me if this is confusing.

Screenshot: https://www.dropbox.com/s/jyjnsnajg81hys2/Screenshot%202019-11-18%2019.19.21.png?dl=0
