### ISSUE TITLE
[QA > iPad Pro] Footer cut off

### ISSUE THREAD

**Issue by jessicasheng15** [vigetlabs/npm#66]
Footer is slightly cut off on iPad Pro.

![image](https://user-images.githubusercontent.com/36860796/67976697-fb640300-fbec-11e9-8d69-359bc41a872e.png)

**Comment by jessicasheng15** [comment]
@justinvandenberg Still lookin' cut off here: https://live-national-public-media-v2.pantheonsite.io/sponsorship/podcast-sponsorship/

**Comment by gracecanfield** [comment]
@jeremyfrank I'm doing some GitHub cleanup and noticed this ticket is still listed as In Code Review on the project board. Is that accurate, or has this been merged to master already?

**Comment by jeremyfrank** [comment]
Hmmm, I honestly don't remember, but one of the updates above shows that the PR was merged.

**Comment by gracecanfield** [comment]
Thanks! In that case, I believe this must have gone to production; I'll close out.
