### ISSUE TITLE
[Visual QA] Listener Portrait Quote Element

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#79]
**Before snapping to mobile:** The listener portrait image should take up the height of the teal box, and both text and image should keep their overall balance when the browser changes size. Take a look at the "What's Inside" panel for an example of a 50/50 panel that responds accordingly: https://www.atlanticphilanthropies.org/insights/insights-books/giving-while-living#what's_inside

Padding at top can be reduced to help w/ the height, and quote should be shortened to suggest to them a shorter length overall. We may need to cap a character count to help w/ the height v. width issue. 

**Nav arrows:**
On hover, the nav arrow element should swap to 100% FFF

**Comment by mindywagner** [comment]
Also, needs to be bug checked - this is happening around iPad witdth:
![Screen Shot 2019-11-01 at 9 36 49 AM](https://user-images.githubusercontent.com/67819/68028985-95c75380-fc8c-11e9-9eca-c52935ab36b9.png)

**Comment by mindywagner** [comment]
Looking great! A few small tweaks:

**Desktop:**
Let's change the top padding from 150px to 100px (leaving bottom padding as 150px) so this visually centers better.
![Screen Shot 2019-11-13 at 10 41 14 AM](https://user-images.githubusercontent.com/67819/68779179-365d3200-0602-11ea-99a5-6030144002a5.png)

________

**Mobile:**
On mobile, let's get rid of the top padding altogether and make the quote text match the comp - here's the buildout adjusted in-browser to 18px with a line height of 1.2 


![Screen Shot 2019-11-13 at 10 47 29 AM](https://user-images.githubusercontent.com/67819/68779691-167a3e00-0603-11ea-8378-ef4061cb92b3.png)

**Comment by justinvandenberg** [comment]
@mindywagner I'm not seeing the extra padding on the top and bottom on mobile. Are you still seeing it?

**Comment by mindywagner** [comment]
Nope, padding seems to be gone now. Weird! 

Text is still reading as 24px though.
