### ISSUE TITLE
[Visual QA] Global - Button widths

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#86]
At mid-size breakpoints, the buttons should still be desktop sized. It should not snap to full width until it's all the way down to a phone-sized breakpoint (maybe around 400px?)

![Screen Shot 2019-11-01 at 10 39 01 AM](https://user-images.githubusercontent.com/67819/68032377-f8701d80-fc93-11e9-8fa6-8609efd793f6.png)

**Comment by justinvandenberg** [comment]
@mindywagner there isn't a current breakpoint that small. The current smallest is 640px, but I can add one at 414px (iPhone Pro). Does that work?

**Comment by mindywagner** [comment]
Yep, that's great!
