### ISSUE TITLE
[Visual QA] Related Work Element 

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#91]
**Desktop:**
- Section headline should be H3/24px (is H2/36px now)
- Padding between detail text and "Read article" link should be 20px (currently closer to 40px)

Padding example:
![Screen Shot 2019-11-01 at 12 46 25 PM](https://user-images.githubusercontent.com/67819/68041075-1fcfe600-fca6-11e9-9dc1-9509d9184bb8.png)

______________________________________________________________________________________________________

**Midsize:** 
Similar to ticket #90 - When scaling, the space between the two elements should be smaller than the side padding. In other words, keep the side padding cushier for as long as you can, with space between the elements tightening. They should never go tighter than 20px. See the News & Insights adjusted spacing (seen in ticket #90 or in Figma > Styles > Components > News & Insights Article Cards for an example of what Insights should also do. )

______________________________________________________________________________________________________

**Mobile:**
- Padding between start of the element & section headline should be 40px - currently closer to 55px  (this is a global mobile style for padding between all sections)
- Padding between detail text & link should be 20px (currently closer to 30px)

Padding example:
![Mobile Work Card Block - 3, 16_9](https://user-images.githubusercontent.com/67819/68041113-38400080-fca6-11e9-8cff-f54fadb69be0.png)

**Comment by justinvandenberg** [comment]
@mindywagner I don't think the % gutter with a minimum is possible with pure CSS. I can drop it down at different break points?

**Comment by mindywagner** [comment]
Yeah, find-tuning it at different breakpoints would be fine then.
