### ISSUE TITLE
[Visual QA] Call to Action Element

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#93]
**Desktop:**
- Padding between top of element and top of headline should be 100px (closer to ~110px) 
- Headline font size should be 36px (currently 48px)

Comp:
![Callout - Headline, Text,   Button](https://user-images.githubusercontent.com/67819/68042303-eea4e500-fca8-11e9-8359-a8055162b8ca.png)

**Comment by justinvandenberg** [comment]
@mindywagner the Cal to Action currently has Y padding of 100px on desktop. I'm noticing across a few tickets. I'll make comments where I see them. 
![Screen Shot 2019-11-07 at 12 56 31 PM](https://user-images.githubusercontent.com/8126358/68424273-dd545080-0160-11ea-97f4-3b36ec7ed2d2.png)

**Comment by mindywagner** [comment]
I think we should leave this one as-is, unless NPM specifically asks to change it. If pressed, we could go as low as 50px top/bottom, but it'll look tight on callouts with more content (like the one on Podcast Sponsorship)
