### ISSUE TITLE
[Visual QA] Simple Quote Carousel

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#94]
**Desktop:** 
- Padding between top of white box and text should be 100px (currently closer to ~115px)
- Padding between bottom of white box and the bottom of the teal background should be 100px (currently closer to 175px)
- Let's set line height for the main quote text to 140% instead of 160%. It renders a big larger in the browser than it did in Figma, and this will better accommodate longer quotes. 

_____________________

**Mid-size:**
**Navigation is missing**
![Screen Shot 2019-11-01 at 1 30 23 PM](https://user-images.githubusercontent.com/67819/68043508-d6829500-fcab-11e9-929e-7496e21f3787.png)

_____________________

**Mobile:**
Carousel navigation needs hover state - button should swap to 100% #fff on hover.

**Comment by justinvandenberg** [comment]
@mindywagner same here.
![Screen Shot 2019-11-07 at 1 18 04 PM](https://user-images.githubusercontent.com/8126358/68424735-d548e080-0161-11ea-88de-14289ee3c697.png)
![Screen Shot 2019-11-07 at 1 17 59 PM](https://user-images.githubusercontent.com/8126358/68424736-d548e080-0161-11ea-9f05-6375ff3bb948.png)

**Comment by mindywagner** [comment]
We could reduce this to 50px

**Comment by justinvandenberg** [comment]
@mindywagner for both the teal and white parts?

**Comment by mindywagner** [comment]
For just the teal - sorry, should have specified.

**Comment by mindywagner** [comment]
NPM has requested a smaller font size for this element. They are using very long quotes. So let's go with the font size used on the homepage - 24px, 1.6 line height.
