### ISSUE TITLE
[Visual QA] Featured Work Element

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#95]
**Desktop:**
- Image is being chopped off on the right side - dimensions for this image might be wrong - the height/width ratio should be what it is in comps
- Featured Work that is immediately followed by Related Work should not have a 100px padding between it and the Related Work. Padding between the Featured & Related sections should only be 50px when the two are stacked, so that they appear to be a single group
- Headline font size should be 36px (currently 18px)

Comp:
![Work Block - Feature   3](https://user-images.githubusercontent.com/67819/68043671-2f522d80-fcac-11e9-837e-6ea025ad83fc.png)

_______________

**Mobile:**
- Padding between the bottom of the Featured Work element and the Related Work element should be 50px. Currently closer to 75px.
- Padding between the headline and the detail text should be 20px (currently closer to 35px)
- Padding between the detail text and the link should be 20px (currently closer to 30px)
- Headline should be Mobile H2/ 36px (currently H3/18px)

Comp:
![Mobile Featured Work](https://user-images.githubusercontent.com/67819/68043854-a5ef2b00-fcac-11e9-9d85-c9a478145528.png)

**Comment by mindywagner** [comment]
The featured work block should be one cohesive element, without a separator or title.  I realize we use a similar block w/ the 3-up work & a headline - can we make it a separate instance or make the separator/headline optional so they can create this? 

![Screen Shot 2019-11-13 at 9 35 26 AM](https://user-images.githubusercontent.com/67819/68773155-0fe6c900-05f9-11ea-9bd2-9297fc720f3a.png)

**Comment by gracecanfield** [comment]
@justinvandenberg Do you mean the heading field on the Related Work block? (bottom component) - that's already optional - see [admin screenshot](https://www.dropbox.com/s/irvpg4ndl6ios37/Screenshot%202019-11-13%2010.26.10.png?dl=0)

**Comment by mindywagner** [comment]
Ah - yep. So if you leave that out, does it leave out the divider? And is NPM the one that put that in?

My goal is that when they're combining a featured work block w/ a 3-up work block, it appears as a single element without dividers, extra headers, etc.

**Comment by justinvandenberg** [comment]
@mindywagner what should we do when a white hero is followed by a white block? Just eliminate the padding from the block?

**Comment by mindywagner** [comment]
Which page is this happening on currently?

**Comment by gracecanfield** [comment]
@mindywagner https://live-national-public-media-v2.pantheonsite.io/

**Comment by mindywagner** [comment]
This is the homepage, blue hero area... and the work is just a 3-up here. Am I looking at the wrong element?

**Comment by gracecanfield** [comment]
@mindywagner So sorry - wrong link 🤦‍♀ - https://live-national-public-media-v2.pantheonsite.io/page-blocks

**Comment by mindywagner** [comment]
Ah, yeah - on pages like that, I think we can transition without the separator because there's a natural visual separation due to the difference in column widths

**Comment by gracecanfield** [comment]
@justinvandenberg See @mindywagner 's comment above

**Comment by gracecanfield** [comment]
I think this is N/A? didn't have the chance to check everything thing, but did confirm that the separator between the two blocks is removed and it still looks good.
