### ISSUE TITLE
[Bug] Product Filtering

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#96]
When I select a primary filter and then try to go back to "All Products" nothing changes. See: 
https://live-national-public-media-v2.pantheonsite.io/products/?platform=video

If I try to select a sub-filter without any products in it, I get a black page without any card area. We should have a blank card area at least ~400px tall with an h1 that says "There are no products matching this criteria."

**Comment by gracecanfield** [comment]
This is a dupe for an existing ticket - closing out.
