### ISSUE TITLE
[Visual/Functional QA] Featured Products Element

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#99]
This element appears to currently be using the Featured Content block, but Featured Products is a different element with different styling & fields. 

- We're missing a text block in the Featured Products element - it should be below the headline and above the 2 featured products
- Cards need updating to match comp
- View all link needed

Buildout:
![Screen Shot 2019-11-01 at 2 56 04 PM](https://user-images.githubusercontent.com/67819/68048865-d7212880-fcb7-11e9-9365-97803697d28f.png)

Comp:
![Product examples](https://user-images.githubusercontent.com/67819/68048795-b22cb580-fcb7-11e9-92ce-4018f49be98b.png)

**Comment by gracecanfield** [comment]
@mindywagner This is already captured in an existing ticket; closing.
